/**
 *  SoftChalk LessonBuilder
 *  ================ DO NOT EDIT ================
 */

q_item=24;
group_item=6;
tableToggle_array=[];
f_done=[];
feed=[];
q_done=[];
scoreQ=[];
qOrder=[];
qOrder[0]=2;
qOrder[1]=3;
qOrder[2]=4;
qOrder[3]=21;
qOrder[4]=5;
qOrder[5]=7;
qOrder[6]=8;
qOrder[7]=9;
qOrder[8]=10;
qOrder[9]=11;
qOrder[10]=12;
qOrder[11]=13;
qOrder[12]=23;
qOrder[13]=14;
qOrder[14]=24;
qOrder[15]=16;
qOrder[16]=20;
qOrder[17]=17;
qOrder[18]=18;
qOrder[19]=1;
num_pages=8;
//groupOrder1=2,3,4
//groupName1=Generation X

//groupPopupTitle1=
//groupOneAtATime1=true
//groupRandom1=false
//groupPoolSize1=3
//groupRetry1=false
//groupShow1=false
//groupScoreSummary1=false
//groupBorder1=true
//groupOrder2=21,5,7,8
//groupName2=Generation Y

//groupPopupTitle2=
//groupOneAtATime2=true
//groupRandom2=false
//groupPoolSize2=4
//groupRetry2=false
//groupShow2=false
//groupScoreSummary2=false
//groupBorder2=true
//groupOrder3=9,10,11
//groupName3=Generation Z

//groupPopupTitle3=
//groupOneAtATime3=true
//groupRandom3=false
//groupPoolSize3=3
//groupRetry3=false
//groupShow3=false
//groupScoreSummary3=false
//groupBorder3=true
//groupOrder4=12,13,23
//groupName4=Hispanic Students

//groupPopupTitle4=
//groupOneAtATime4=true
//groupRandom4=false
//groupPoolSize4=3
//groupRetry4=false
//groupShow4=false
//groupScoreSummary4=false
//groupBorder4=true
//groupOrder5=14,24,16
//groupName5=International Students

//groupPopupTitle5=
//groupOneAtATime5=true
//groupRandom5=false
//groupPoolSize5=3
//groupRetry5=false
//groupShow5=false
//groupScoreSummary5=false
//groupBorder5=true
//groupOrder6=20,17,18
//groupName6=Disabaled Population

//groupPopupTitle6=
//groupOneAtATime6=true
//groupRandom6=false
//groupPoolSize6=3
//groupRetry6=false
//groupShow6=false
//groupScoreSummary6=false
//groupBorder6=true
scorm_completed_status=true;

//q_num=2;
inline_feedback2=true;
q_done[2]=false;
q_value2=6;
scoreQ[2]="yes";
mc_items2=6;
//ra_items2=1;
q_type2=3;
theQuestion2="<p>What are some of the Traits of Gen Xers? Choose all that apply.</p>";
showCorrect2="no";
showHint2="no";
showFeedbackIndividual2="yes";
case_sensitive2="false";
partial_credit2=true;
feedbackRight2="<p>Right! Good job!</p>";
feedbackWrong2="<p>Sorry, incorrect answer. Go through the Traits of Gen Xers again.</p>";
feedbackPartial2="<p>Partially correct.</p><p>Go through the Traits of Gen Xers again.</p>";
hint2="";
feedbackIndividual2=[];
feedbackIndividual2[0]="<p>Yes, Generation X competent with technology but prefer communications via email and phone.</p>";
feedbackIndividual2[1]="<p>Are you sure Generation X rarely defy authority and micromanagers? Isn't it the other way?</p><p>&nbsp;</p>";
feedbackIndividual2[2]="<p>Yes, Generation X are driven by reality of how a course will help them in the real world.</p><p>&nbsp;</p>";
feedbackIndividual2[3]="<p>Yes, Generation X are resourceful problem solvers.</p><p>&nbsp;</p>";
feedbackIndividual2[4]="<p>Yes, Generation X are loyal to individuals, not organizations.</p><p>&nbsp;</p>";
feedbackIndividual2[5]="<p>Yes, Generation X are entrepreneurial thinkers.</p><p>&nbsp;</p>";
right_answers2=[];
right_answers2[0]="a,c,d,e,f";
answer_choices2=[];
answer_choices2[0]="<p>Competent with technology but prefer communications via email and phone.</p>";
answer_choices2[1]="<p>Rarely defy authority and micromanagers.</p>";
answer_choices2[2]="<p>Driven by reality of how a course will help them in the real world.</p>";
answer_choices2[3]="<p>Resourceful problem solvers.</p>";
answer_choices2[4]="<p>Loyal to individuals, not organizations.</p>";
answer_choices2[5]="<p>Entrepreneurial thinkers.</p>";
tableToggle_array[2]=false;
f_done[2]=false;
feed[2]=false;
//allowRetry2=true;
//groupID2=1;

//q_num=3;
inline_feedback3=true;
q_done[3]=false;
q_value3=6;
scoreQ[3]="yes";
mc_items3=6;
//ra_items3=1;
q_type3=3;
theQuestion3="<p>Jane was born in 1972. She is one of the adult learners in your classroom. Which of the following tips would you apply to your teaching to meet her needs? Select all that apply.</p>";
showCorrect3="no";
showHint3="no";
showFeedbackIndividual3="yes";
case_sensitive3="false";
partial_credit3=true;
feedbackRight3="<p>Right! Good job!</p>";
feedbackWrong3="<p>Sorry, incorrect answer. Please go through the practical tips of Generation X again.</p>";
feedbackPartial3="<p>Partially correct.</p>";
hint3="";
feedbackIndividual3=[];
feedbackIndividual3[0]="<p>Indeed, more than likely, Jane would appreciate these instructional methods.</p>";
feedbackIndividual3[1]="<p>Indeed, more than likely, Jane would appreciate connecting the material to real world scenarios.</p>";
feedbackIndividual3[2]="<p>Unfortunately, Jane may get frustrated with vague instructions. Instead, you may want to provide clear instructions.</p>";
feedbackIndividual3[3]="<p>Indeed, metacognitive activities are useful for solidifying learning.</p>";
feedbackIndividual3[4]="<p>On the contrary, explain how group work benefits their learning and how it connects to real work situations.</p>";
feedbackIndividual3[5]="<p>Individual work is always useful in challenging learners' cognitive growth.</p>";
right_answers3=[];
right_answers3[0]="a,b,d,f";
answer_choices3=[];
answer_choices3[0]="<p>Use games and case studies in the classroom</p>";
answer_choices3[1]="<p>Connect assignments to real world situations</p>";
answer_choices3[2]="<p>Provide vague instructions for assignments and activities and let Jane figure out what to do.</p>";
answer_choices3[3]="<p>Add brief opportunities for her to reflect on her learning</p>";
answer_choices3[4]="<p>When group work is required, let students get started without explaining the rationale and benefits of such activities</p>";
answer_choices3[5]="<p>Provide opportunities for individual work</p>";
tableToggle_array[3]=false;
f_done[3]=false;
feed[3]=false;
//allowRetry3=true;
//groupID3=1;

//q_num=4;
inline_feedback4=true;
q_done[4]=false;
q_value4=2;
scoreQ[4]="yes";
mc_items4=2;
//ra_items4=1;
q_type4=2;
theQuestion4="<p>One of the learning preference that Gen Xers like is engaging in direct or immediate communication through emails and phone conversations.</p>";
showCorrect4="no";
showHint4="no";
showFeedbackIndividual4="no";
case_sensitive4="false";
partial_credit4=false;
feedbackRight4="<p>Right! Good job! One of the learning preference that can be applied to Baby Busters, also known as Generation X, is engaging in direct or immediate communication through emails and phones.</p>";
feedbackWrong4="<p>Sorry, incorrect answer. One of the learning preference that can be applied to Baby Busters, also known as Generation X, is engaging in direct or immediate communication through emails and phones.</p>";
feedbackPartial4="Partially correct.";
hint4="";
feedbackIndividual4=[];
right_answers4=[];
right_answers4[0]="true";
answer_choices4=[];
answer_choices4[0]="True";
answer_choices4[1]="False";
tableToggle_array[4]=false;
f_done[4]=false;
feed[4]=false;
//allowRetry4=true;
//groupID4=1;

//q_num=21;
inline_feedback21=true;
q_done[21]=false;
q_value21=3;
scoreQ[21]="yes";
mc_items21=1;
//ra_items21=1;
q_type21=10;
theQuestion21="<p>If you were born near the end of one generation and at the beginning of the next, and you feel that you have a mix of characteristics of both adjacent generations but don't resemble the typical traits of the middle of the adjacent generations, you might be a [Cusper].</p>";
showCorrect21="no";
showHint21="no";
showFeedbackIndividual21="no";
case_sensitive21="true";
partial_credit21=false;
feedbackRight21="<p>Right! Good job! If you were born near the end of one generation and at the beginning of the next, and you feel that you have a mix of characteristics of both adjacent generations but don't resemble the typical traits of the middle of the adjacent generations, you might be a <strong>Cusper</strong>.</p>";
feedbackWrong21="<p>Sorry, incorrect answer. If you were born near the end of one generation and at the beginning of the next, and you feel that you have a mix of characteristics of both adjacent generations but don't resemble the typical traits of the middle of the adjacent generations, you might be a <strong>Cusper</strong>.</p>";
feedbackPartial21="<p>Partially correct.</p>";
hint21="";
feedbackIndividual21=[];
right_answers21=[];
right_answers21[0]="";
answer_choices21=[];
answer_choices21[0]="";
tableToggle_array[21]=false;
f_done[21]=false;
feed[21]=false;
//allowRetry21=true;
//groupID21=2;

//q_num=5;
inline_feedback5=true;
q_done[5]=false;
q_value5=3;
scoreQ[5]="yes";
mc_items5=4;
//ra_items5=1;
q_type5=1;
theQuestion5="<p>What is the most common name for Generation Y? Select the best possible answer.</p>";
showCorrect5="no";
showHint5="no";
showFeedbackIndividual5="yes";
case_sensitive5="false";
partial_credit5=false;
feedbackRight5="<p>Right! Good job!</p>";
feedbackWrong5="<p>Sorry, incorrect answer.</p>";
feedbackPartial5="Partially correct.";
hint5="";
feedbackIndividual5=[];
feedbackIndividual5[0]="";
feedbackIndividual5[1]="";
feedbackIndividual5[2]="";
feedbackIndividual5[3]="";
right_answers5=[];
right_answers5[0]="c";
answer_choices5=[];
answer_choices5[0]="<p>Generation Us</p>";
answer_choices5[1]="<p>Internet Generation</p>";
answer_choices5[2]="<p>Millennials</p>";
answer_choices5[3]="<p>Leave No One Behind</p>";
tableToggle_array[5]=false;
f_done[5]=false;
feed[5]=false;
//allowRetry5=true;
//groupID5=2;

//q_num=7;
inline_feedback7=true;
q_done[7]=false;
q_value7=6;
scoreQ[7]="yes";
mc_items7=6;
//ra_items7=1;
q_type7=3;
theQuestion7="<p>You are asked to teach a class and recognize that most students are Millennials. What are some of the common traits of Millennials that may influence how you adjust your teaching strategies? Select all that apply.</p>";
showCorrect7="no";
showHint7="no";
showFeedbackIndividual7="yes";
case_sensitive7="false";
partial_credit7=true;
feedbackRight7="<p>Right! Good job!</p>";
feedbackWrong7="<p>Sorry, incorrect answer.</p>";
feedbackPartial7="<p>Partially correct.</p>";
hint7="";
feedbackIndividual7=[];
feedbackIndividual7[0]="<p>Indeed, that's a common trait of Millennials.</p>";
feedbackIndividual7[1]="<p>Indeed, that's a common trait of Millennials.</p>";
feedbackIndividual7[2]="<p>Indeed, that's a common trait of Millennials.</p>";
feedbackIndividual7[3]="<p>Indeed, that's a common trait of Millennials.</p>";
feedbackIndividual7[4]="";
feedbackIndividual7[5]="<p>Indeed, that's a common trait of Millennials.</p>";
right_answers7=[];
right_answers7[0]="a,b,c,d,f";
answer_choices7=[];
answer_choices7[0]="<p>Most students are highly visual learners who also like humor.</p>";
answer_choices7[1]="<p>Students expect immediate feedback to know that they are on the right track.</p>";
answer_choices7[2]="<p>Students have short attention span and are easily distracted by social media and notifications.</p>";
answer_choices7[3]="<p>Students are team-oriented and enjoy collaborating with others.</p>";
answer_choices7[4]="<p>Students like to sacrifice their personal life.</p>";
answer_choices7[5]="<p>They use technology throughout the day to remain connected to the world and one another</p>";
tableToggle_array[7]=false;
f_done[7]=false;
feed[7]=false;
//allowRetry7=true;
//groupID7=2;

//q_num=8;
inline_feedback8=true;
q_done[8]=false;
q_value8=4;
scoreQ[8]="yes";
mc_items8=4;
//ra_items8=1;
q_type8=3;
theQuestion8="<p>What are some of the learning preferences of Generation Y? Select all that apply.</p>";
showCorrect8="no";
showHint8="no";
showFeedbackIndividual8="yes";
case_sensitive8="false";
partial_credit8=true;
feedbackRight8="<p>Right! Good job!</p>";
feedbackWrong8="<p>Sorry, incorrect answer.</p>";
feedbackPartial8="<p>Partially correct.</p>";
hint8="";
feedbackIndividual8=[];
feedbackIndividual8[0]="<p>Indeed, you may want to develop collaborative activities and assignments to meet their needs.</p>";
feedbackIndividual8[1]="<p>Indeed! You may want to give them options for demonstrating their skills and knowledge.</p>";
feedbackIndividual8[2]="<p>For sure! Perhaps most learners want to be engaged and not only the Millennials.</p>";
feedbackIndividual8[3]="<p>That's correct. In fact, most learners need to hear the rationale behind activities regardless of the generational belonging.</p>";
right_answers8=[];
right_answers8[0]="a,b,c,d";
answer_choices8=[];
answer_choices8[0]="<p>Extremely team-oriented and enjoy collaborating and building friendships with colleagues.</p>";
answer_choices8[1]="<p>They like customizing the course to fit their preferences (such as selecting a project, topic, platform, etc.).</p>";
answer_choices8[2]="<p>Expect the instructor to provide a very engaging, structured environment.</p>";
answer_choices8[3]="<p>Need to hear rationale behind instructions.</p>";
tableToggle_array[8]=false;
f_done[8]=false;
feed[8]=false;
//allowRetry8=true;
//groupID8=2;

//q_num=9;
inline_feedback9=true;
q_done[9]=false;
q_value9=6;
scoreQ[9]="yes";
mc_items9=6;
//ra_items9=1;
q_type9=3;
theQuestion9="<p>What are some of the Gen Z traits that may influence the applicable teaching strategies? Select all that apply.</p>";
showCorrect9="no";
showHint9="no";
showFeedbackIndividual9="yes";
case_sensitive9="false";
partial_credit9=true;
feedbackRight9="<p>Right! Good job!</p>";
feedbackWrong9="<p>Sorry, incorrect answer.</p>";
feedbackPartial9="<p>Partially correct.</p>";
hint9="";
feedbackIndividual9=[];
feedbackIndividual9[0]="<p>That is a correct statement in terms of Gen Z traits.</p>";
feedbackIndividual9[1]="<p>That is a correct statement in terms of Gen Z traits.</p>";
feedbackIndividual9[2]="<p>That is a correct statement in terms of Gen Z traits.</p>";
feedbackIndividual9[3]="<p>That is a correct statement in terms of Gen Z traits.</p>";
feedbackIndividual9[4]="<p>On the contrary! They are more diverse than any other generation.</p>";
feedbackIndividual9[5]="<p>That is a correct statement in terms of Gen Z traits.</p>";
right_answers9=[];
right_answers9[0]="a,b,c,d,f";
answer_choices9=[];
answer_choices9[0]="<p>They prefer learning that is meaningful; their work ethic is more realistic than what Gen Y represents.</p>";
answer_choices9[1]="<p>They are competitive, entrepreneurial, trustworthy, tolerant and less motivated by money.</p>";
answer_choices9[2]="<p>Gen Z learners are more tech-savvy than any previous generation.</p>";
answer_choices9[3]="<p>They are fast-paced in processing information and materials and do not hesitate to ask ask questions</p>";
answer_choices9[4]="<p>They are ethnically less diverse than any previous generation.</p>";
answer_choices9[5]="<p>They are tactile learners with shorter attention span.</p>";
tableToggle_array[9]=false;
f_done[9]=false;
feed[9]=false;
//allowRetry9=true;
//groupID9=3;

//q_num=10;
inline_feedback10=true;
q_done[10]=false;
q_value10=2;
scoreQ[10]="yes";
mc_items10=2;
//ra_items10=1;
q_type10=2;
theQuestion10="<p>Learning is passive experience for Gen Z. This generation is unaccustomed to rapid diffusion of information presented in a graphically and technologically sophisticated style.</p>";
showCorrect10="no";
showHint10="no";
showFeedbackIndividual10="no";
case_sensitive10="false";
partial_credit10=false;
feedbackRight10="<p>Right! Good job!</p>";
feedbackWrong10="<p>Sorry, incorrect answer.</p>";
feedbackPartial10="Partially correct.";
hint10="";
feedbackIndividual10=[];
right_answers10=[];
right_answers10[0]="false";
answer_choices10=[];
answer_choices10[0]="True";
answer_choices10[1]="False";
tableToggle_array[10]=false;
f_done[10]=false;
feed[10]=false;
//allowRetry10=true;
//groupID10=3;

//q_num=11;
inline_feedback11=true;
q_done[11]=false;
q_value11=6;
scoreQ[11]="yes";
mc_items11=6;
//ra_items11=1;
q_type11=3;
theQuestion11="<p>You have more and more Gen Zs in your classes. What are some of the teaching tips that are recommended to use when teaching them? Select all that apply.</p>";
showCorrect11="no";
showHint11="no";
showFeedbackIndividual11="yes";
case_sensitive11="false";
partial_credit11=true;
feedbackRight11="<p>Right! Good job!</p>";
feedbackWrong11="<p>Sorry, incorrect answer.</p>";
feedbackPartial11="<p>Partially correct.</p>";
hint11="";
feedbackIndividual11=[];
feedbackIndividual11[0]="<p>Excellent idea!</p>";
feedbackIndividual11[1]="<p>Indeed, all these are great ideas to implement.</p>";
feedbackIndividual11[2]="<p>Indeed, all these are great ideas to implement.</p>";
feedbackIndividual11[3]="<p>Indeed, all these are great ideas to implement.</p>";
feedbackIndividual11[4]="<p>Indeed, this is a great idea to implement.</p>";
feedbackIndividual11[5]="<p>Indeed, this is a great idea to implement.</p>";
right_answers11=[];
right_answers11[0]="a,b,c,d,e,f";
answer_choices11=[];
answer_choices11[0]="<p>Co-create content with learners</p>";
answer_choices11[1]="<p>Utilize peer coaching, action mapping, problem-based learning, storytelling, and guided self-reflection</p>";
answer_choices11[2]="<p>Include microlearning, videos, social sharing, gamification, and on-demand content in the course</p>";
answer_choices11[3]="<p>Invite subject matter experts, trainers, and other professionals to create high impact learning opportunities</p>";
answer_choices11[4]="<p>Use in-class session as learning labs</p>";
answer_choices11[5]="<p>Develop relevant learning experiences that utilizes technology</p>";
tableToggle_array[11]=false;
f_done[11]=false;
feed[11]=false;
//allowRetry11=true;
//groupID11=3;

//q_num=12;
inline_feedback12=true;
q_done[12]=false;
q_value12=6;
scoreQ[12]="yes";
mc_items12=6;
//ra_items12=1;
q_type12=3;
theQuestion12="<p>What are some of the learning traits and preferences that can be applied to classes where Hispanic students are present?</p>";
showCorrect12="no";
showHint12="no";
showFeedbackIndividual12="yes";
case_sensitive12="false";
partial_credit12=true;
feedbackRight12="<p>Right! Good job!</p>";
feedbackWrong12="<p>Sorry, incorrect answer.</p>";
feedbackPartial12="<p>Partially correct.</p>";
hint12="";
feedbackIndividual12=[];
feedbackIndividual12[0]="<p>On the contrary! They are respectful of authority in general.</p>";
feedbackIndividual12[1]="<p>That's correct! Hispanics, too, wish to take part in meaningful learning that is applicable to their lives.</p>";
feedbackIndividual12[2]="<p>Hispanics in general represent a family-centered culture.</p>";
feedbackIndividual12[3]="<p>Not really. They also learn from peers.</p>";
feedbackIndividual12[4]="<p>That's right!</p>";
feedbackIndividual12[5]="<p>For sure! They want to see themselves represented in materials and be able to relate to them.</p>";
right_answers12=[];
right_answers12[0]="b,e,f";
answer_choices12=[];
answer_choices12[0]="<p>Hispanic students have less respect to authority figures.</p>";
answer_choices12[1]="<p>Hispanics students wish to connect the knowledge learned in the classroom to the home, community, and professional environment</p>";
answer_choices12[2]="<p>One value that is of paramount importance in most Hispanic cultures is commitment to the location where they live.</p>";
answer_choices12[3]="<p>Students like to learn on their own without interacting with peers.</p>";
answer_choices12[4]="<p>Hispanic adolescents have a greater inclination to adopt their parents' religious beliefs, lifestyle, and stereotyped sex roles.</p>";
answer_choices12[5]="<p>Students desire materials that are linguistically as well as culturally appropriate.</p>";
tableToggle_array[12]=false;
f_done[12]=false;
feed[12]=false;
//allowRetry12=true;
//groupID12=4;

//q_num=13;
inline_feedback13=true;
q_done[13]=false;
q_value13=10;
scoreQ[13]="yes";
mc_items13=10;
//ra_items13=1;
q_type13=3;
theQuestion13="<p>Camila is a Hispanic student who has just transferred to your class in the middle of a semester. While introducing herself, she says she is bilingual, but prefers Spanish rather than English. After few days, you realize that she seems discouraged because she is not grasping all content during class and may need some help.</p><p>Look at list below and select all methods (or tips) that you can use so Camila can learn better in your course.</p>";
showCorrect13="no";
showHint13="no";
showFeedbackIndividual13="yes";
case_sensitive13="false";
partial_credit13=true;
feedbackRight13="<p>Right! Good job!</p>";
feedbackWrong13="<p>Sorry, incorrect answer.</p>";
feedbackPartial13="<p>Partially correct.</p>";
hint13="";
feedbackIndividual13=[];
feedbackIndividual13[0]="<p>Indeed, the Writing Center may be able to assist.</p>";
feedbackIndividual13[1]="<p>Yes! That actually includes a variety of opportunities that could help Camilla.</p>";
feedbackIndividual13[2]="";
feedbackIndividual13[3]="";
feedbackIndividual13[4]="<p>Although the Translator may help her to improve her language skills, that will not teach her the long list of skills that make one career ready.</p>";
feedbackIndividual13[5]="<p>Closed captioning is helpful to the majority of learners to follow what is being said in the video, especially students whose first language is not English.</p>";
feedbackIndividual13[6]="<p>Right! Recognize that she may articulate her thoughts more effectively in writing than verbally.</p>";
feedbackIndividual13[7]="<p>That's a great idea not only for Camilla but others as well.</p>";
feedbackIndividual13[8]="<p>On the contrary, she needs feedback that is tailored to her developmental level.</p>";
feedbackIndividual13[9]="<p>These are fantastic options to guide her.</p>";
right_answers13=[];
right_answers13[0]="a,b,c,d,f,g,h,j";
answer_choices13=[];
answer_choices13[0]="<p>Refer her to the Writing Center to improve her English skills.</p><p>&nbsp;</p>";
answer_choices13[1]="<p>Develop proficiency in English by providing Camila with rich language experiences that integrate speaking, listening, reading, and writing.</p>";
answer_choices13[2]="<p>Offer learning materials that are both in English and Spanish.</p>";
answer_choices13[3]="<p>Develop individual projects where she can work on her own to catch up but still demonstrate the same skills and knowledge.</p>";
answer_choices13[4]="<p>Tell her to use Google Translator so that she can become career ready on her own at her own pace.</p>";
answer_choices13[5]="<p>Offer her videos that contain closed captioning to help her with understanding the content.</p>";
answer_choices13[6]="<p>Ask her to turn in more work in writing than verbally so that she has time to form her thoughts.</p>";
answer_choices13[7]="<p>Emphasize Camila's learning style strengths and match instructional resources and methods to her learning style preferences.</p>";
answer_choices13[8]="<p>Decrease her anxiety by simply assigning her the grade she earned without much feedback and constructive criticism.</p>";
answer_choices13[9]="<p>Provide examples, demonstrations, and optional resources that meet her needs.</p>";
tableToggle_array[13]=false;
f_done[13]=false;
feed[13]=false;
//allowRetry13=true;
//groupID13=4;

//q_num=23;
inline_feedback23=true;
q_done[23]=false;
q_value23=2;
scoreQ[23]="yes";
mc_items23=2;
//ra_items23=1;
q_type23=2;
theQuestion23="<p>Establishing a welcoming community through frequent discussions, small group work, and peer-evaluation activities help Hispanics develop social, academic, and communication skills.</p>";
showCorrect23="no";
showHint23="no";
showFeedbackIndividual23="no";
case_sensitive23="false";
partial_credit23=false;
feedbackRight23="<p>Right! Good job!</p>";
feedbackWrong23="<p>Sorry, incorrect answer.</p>";
feedbackPartial23="Partially correct.";
hint23="";
feedbackIndividual23=[];
right_answers23=[];
right_answers23[0]="true";
answer_choices23=[];
answer_choices23[0]="True";
answer_choices23[1]="False";
tableToggle_array[23]=false;
f_done[23]=false;
feed[23]=false;
//allowRetry23=true;
//groupID23=4;

//q_num=14;
inline_feedback14=true;
q_done[14]=false;
q_value14=6;
scoreQ[14]="yes";
mc_items14=6;
//ra_items14=1;
q_type14=3;
theQuestion14="<p>Below are some statements regarding international students. Select all the statements that are true for international students in general.</p>";
showCorrect14="no";
showHint14="no";
showFeedbackIndividual14="yes";
case_sensitive14="false";
partial_credit14=true;
feedbackRight14="<p>Right! Good job!</p>";
feedbackWrong14="<p>Sorry, incorrect answer.</p>";
feedbackPartial14="<p>Partially correct.</p>";
hint14="";
feedbackIndividual14=[];
feedbackIndividual14[0]="<p>That's right!</p>";
feedbackIndividual14[1]="<p>All students expect an enriching experience when coming to ISU.</p>";
feedbackIndividual14[2]="<p>Unfortunately, that's not the situation.</p>";
feedbackIndividual14[3]="<p>Sure! They also want to be prepared for their careers as the rest of the student body.</p>";
feedbackIndividual14[4]="<p>On the contrary! They normally face challenges due to their level of English knowledge.</p>";
feedbackIndividual14[5]="<p>These students can't work off campus without appropriate visa status.</p>";
right_answers14=[];
right_answers14[0]="a,d";
answer_choices14=[];
answer_choices14[0]="<p>Academically, students arrive with positive and confident personal expectations of success.</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>";
answer_choices14[1]="<p>The minority of the international students expect a rewarding and enriching experience.</p>";
answer_choices14[2]="<p>All international students receive family support, both economic and psychological.</p>";
answer_choices14[3]="<p>International students perceive career development and job preparation as one of their important needs.</p>";
answer_choices14[4]="<p>All international students are confident about their English speaking and writing skills.</p>";
answer_choices14[5]="<p>International students are allowed to work in this country even outside of the campus environment.</p>";
tableToggle_array[14]=false;
f_done[14]=false;
feed[14]=false;
//allowRetry14=true;
//groupID14=5;

//q_num=24;
inline_feedback24=true;
q_done[24]=false;
q_value24=2;
scoreQ[24]="yes";
mc_items24=2;
//ra_items24=1;
q_type24=2;
theQuestion24="<p>International students represent added value to your courses and other students as they can share a multicultural perspective of the world without having to travel to all those destinations.</p>";
showCorrect24="yes";
showHint24="no";
showFeedbackIndividual24="no";
case_sensitive24="false";
partial_credit24=false;
feedbackRight24="<p>Right! Good job! A feeling of solitude is a factor that hinders international student's online learning. They tend to experience high levels of isolation in both traditional and online classes, online courses make them feel more isolated.</p>";
feedbackWrong24="<p>Sorry, incorrect answer. Remember, a feeling of solitude is a factor that hinders international student's online learning. They tend to experience high levels of isolation in both traditional and online classes, online courses make them feel more isolated.</p>";
feedbackPartial24="Partially correct.";
hint24="";
feedbackIndividual24=[];
right_answers24=[];
right_answers24[0]="true";
answer_choices24=[];
answer_choices24[0]="True";
answer_choices24[1]="False";
tableToggle_array[24]=false;
f_done[24]=false;
feed[24]=false;
//allowRetry24=true;
//groupID24=5;

//q_num=16;
inline_feedback16=true;
q_done[16]=false;
q_value16=10;
scoreQ[16]="yes";
mc_items16=10;
//ra_items16=1;
q_type16=3;
theQuestion16="<p>You have some international students in your class. Each of then is from a different country, and it is their first semester in the States. What are some of the practical tips that may help faculty understand and educate them better in their classes? Select all that apply.</p>";
showCorrect16="no";
showHint16="no";
showFeedbackIndividual16="yes";
case_sensitive16="false";
partial_credit16=true;
feedbackRight16="<p>Right! Good job!</p>";
feedbackWrong16="<p>Sorry, incorrect answer.</p>";
feedbackPartial16="<p>Partially correct.</p>";
hint16="";
feedbackIndividual16=[];
feedbackIndividual16[0]="<p>That's certainly correct!</p>";
feedbackIndividual16[1]="<p>Perfect idea to prevent their isolation.</p>";
feedbackIndividual16[2]="<p>While this may be a good strategy to encourage them, try to focus on what they have to say/contribute instead on their language abilities or accents.</p>";
feedbackIndividual16[3]="<p>That's right!</p>";
feedbackIndividual16[4]="<p>That's incorrect. Many students come to the States and express that they have not been taught to keep academic integrity at a high level.</p>";
feedbackIndividual16[5]="<p>Yes, that's correct!</p>";
feedbackIndividual16[6]="<p>Unfortunately, that's not correct.</p>";
feedbackIndividual16[7]="<p>That's right! In an ideal situation, that is what you would do.</p>";
feedbackIndividual16[8]="<p>It is best practice to learn the names of each student regardless of their status.</p>";
feedbackIndividual16[9]="<p>Excellent idea!</p>";
right_answers16=[];
right_answers16[0]="a,b,d,f,h,j";
answer_choices16=[];
answer_choices16[0]="<p>Avoid interpreting their low engagement as disengagement because they may need to absorb the information before they feel confident to speak up.</p>";
answer_choices16[1]="<p>Assigns students to groups so that international students are not picked last by their peers due to their language challenges.</p>";
answer_choices16[2]="<p>Keep saying, &quot;Your English is already really good.&quot; This will encourage them.</p>";
answer_choices16[3]="<p>Using Universal Design Principles, you can promote language learning by providing closed captions and transcripts for presentations, video, lectures, etc.</p>";
answer_choices16[4]="<p>You do not have to discuss academic integrity policies in detail because all country have same levels of expectations.</p>";
answer_choices16[5]="<p>You can provide audio and visual supplemental materials to help students understand concepts and improve their English listening and speaking skills.</p>";
answer_choices16[6]="<p>Clarifying American pop culture references for international students is not important because they all already know what you are referring to.</p>";
answer_choices16[7]="<p>You should use both synchronous and asynchronous communication tools.</p>";
answer_choices16[8]="<p>You do not have to learn the names of international students.</p>";
answer_choices16[9]="<p>Incorporate cultural differences into instruction and turn them into teachable moments.</p>";
tableToggle_array[16]=false;
f_done[16]=false;
feed[16]=false;
//allowRetry16=true;
//groupID16=5;

//q_num=20;
inline_feedback20=true;
q_done[20]=false;
q_value20=4;
scoreQ[20]="yes";
mc_items20=4;
//ra_items20=4;
q_type20=5;
theQuestion20="<p>Match some of the disabilities with its example.</p>";
showCorrect20="no";
showHint20="no";
showFeedbackIndividual20="no";
case_sensitive20="false";
partial_credit20=true;
feedbackRight20="<p>Right! Good job!</p>";
feedbackWrong20="<p>Sorry, incorrect answer.</p>";
feedbackPartial20="<p>Partially correct.</p>";
hint20="";
feedbackIndividual20=[];
right_answers20=[];
right_answers20[0]="0";
right_answers20[1]="2";
right_answers20[2]="1";
right_answers20[3]="3";
answer_choices20=[];
answer_choices20[0]="<p>dyslexia, dysgraphia</p>";
answer_choices20[1]="<p>congenital heart failure, rheumatoid arthritis, fibromyalgia, psoriasis</p>";
answer_choices20[2]="<p>wheelchair-bound, CP that involves hands, fingers, mobility issues as well as permanent injuries</p>";
answer_choices20[3]="<p>depression, anxiety</p>";
tableToggle_array[20]=false;
f_done[20]=false;
feed[20]=false;
//items_to_match20[0]="<p>Learning Disability</p>";
//items_to_match20[1]="<p>Physical Disability</p>";
//items_to_match20[2]="<p>Chronic Medical Conditions</p>";
//items_to_match20[3]="<p>Psychological Disability</p>";
//allowRetry20=true;
//groupID20=6;

//q_num=17;
inline_feedback17=true;
q_done[17]=false;
q_value17=2;
scoreQ[17]="yes";
mc_items17=2;
//ra_items17=1;
q_type17=2;
theQuestion17="<p>Is the statement below true or false?</p><p>Not all students who identify and register with Student Services use the accommodation(s) for which they qualify during their academic career at ISU?</p>";
showCorrect17="no";
showHint17="no";
showFeedbackIndividual17="no";
case_sensitive17="false";
partial_credit17=false;
feedbackRight17="<p>Right! Good job!</p>";
feedbackWrong17="<p>Sorry, incorrect answer.</p>";
feedbackPartial17="Partially correct.";
hint17="";
feedbackIndividual17=[];
right_answers17=[];
right_answers17[0]="true";
answer_choices17=[];
answer_choices17[0]="True";
answer_choices17[1]="False";
tableToggle_array[17]=false;
f_done[17]=false;
feed[17]=false;
//allowRetry17=true;
//groupID17=6;

//q_num=18;
inline_feedback18=true;
q_done[18]=false;
q_value18=10;
scoreQ[18]="yes";
mc_items18=10;
//ra_items18=1;
q_type18=3;
theQuestion18="<p>Jeanette, Nicole, Kevin, Hillary and Brady are some of your students in your class. Jeanette and Nicole have intellectual disabilities; they have a paraprofessional who accompanies them to selected regular education classrooms, providing instructional support. Nicole is identified with socio-emotional disability and receives special education services for both language arts and mathematics. Kevin is diagnosed with autism, exhibits difficulties in social skills, and is high functioning cognitively. Hillary and Brady have specific learning disabilities and receive special education services for both language arts and mathematics.</p><p>What are some of the practical tips that you can use in your class to make learning easier for them and some other disabled students?</p>";
showCorrect18="no";
showHint18="no";
showFeedbackIndividual18="yes";
case_sensitive18="false";
partial_credit18=true;
feedbackRight18="<p>Right! Good job!</p>";
feedbackWrong18="<p>Sorry, incorrect answer.</p>";
feedbackPartial18="<p>Partially correct.</p>";
hint18="";
feedbackIndividual18=[];
feedbackIndividual18[0]="<p>That's a fantastic way to support our disabled population as well as other students.</p>";
feedbackIndividual18[1]="<p>That's a fantastic way to support our disabled population as well as other students.</p>";
feedbackIndividual18[2]="<p>That's a fantastic way to support our disabled population as well as other students.</p>";
feedbackIndividual18[3]="<p>That's a fantastic way to support our disabled population as well as other students.</p>";
feedbackIndividual18[4]="<p>That's a fantastic way to support our disabled population as well as other students.</p>";
feedbackIndividual18[5]="<p>That's a fantastic way to support our disabled population as well as other students.</p>";
feedbackIndividual18[6]="<p>That's a fantastic way to support our disabled population as well as other students.</p>";
feedbackIndividual18[7]="<p>On the contrary! Encourage them to disclose their disabilities.</p>";
feedbackIndividual18[8]="<p>That's a fantastic way to support our disabled population as well as other students.</p>";
feedbackIndividual18[9]="<p>That's a fantastic way to support our disabled population as well as other students.</p>";
right_answers18=[];
right_answers18[0]="a,b,c,d,e,f,g,i,j";
answer_choices18=[];
answer_choices18[0]="<p>Connect with disabled students enrolled in your courses and ask them about their preferred instructional/learning strategies.</p><p>&nbsp;</p>";
answer_choices18[1]="<p>Regarding course materials, consider colors, fonts, and formats that are easily viewed by students with low vision or a form of color blindness and avoid using websites that have several flash-based visuals that may cause seizure.</p>";
answer_choices18[2]="<p>Post course materials, assignments, and deadlines with advanced notice because it allows students time to plan for accommodations and workload.</p>";
answer_choices18[3]="<p>Use multiple formats for instruction for delivering content because students learn different ways. You can make outlines or recordings available online or explain in a video all printed assignments.</p>";
answer_choices18[4]="<p>Prepare alternative assignments because some students may have difficulties with the requested method of delivery such as presentation and public speaking.</p>";
answer_choices18[5]="<p>Think of multiple ways students may be able to participate without feeling excluded instead of assuming what activities they can or cannot do.</p>";
answer_choices18[6]="<p>Remove negative portrayals of the members of the disabled population.</p>";
answer_choices18[7]="<p>Encourage students to hide their disabilities at Student Disability Services.</p>";
answer_choices18[8]="<p>Make disabled students feel like any other student by using positive reinforcement and giving them personalized attention during the learning process.</p>";
answer_choices18[9]="<p>Follow universal design principles and create assessments that offer options for demonstrating relevant knowledge and skills. Let students choose the method to deliver their representative project.</p>";
tableToggle_array[18]=false;
f_done[18]=false;
feed[18]=false;
//allowRetry18=true;
//groupID18=6;

//q_num=1;
inline_feedback1=true;
q_done[1]=false;
q_value1=0;
scoreQ[1]="no";
mc_items1=0;
//ra_items1=0;
q_type1=8;
theQuestion1="<p>What is your overall impression of this lesson? Was it useful? What are the strengths of it? What are the weaknesses of this lesson? What would you change to make it more effective?</p>";
showCorrect1="no";
showHint1="no";
showFeedbackIndividual1="no";
case_sensitive1="false";
partial_credit1=false;
feedbackRight1="";
feedbackWrong1="";
feedbackPartial1="Partially correct.";
hint1="";
feedbackIndividual1=[];
right_answers1=[];
right_answers1[0]="";
answer_choices1=[];
answer_choices1[0]="no choices";
tableToggle_array[1]=false;
f_done[1]=false;
feed[1]=false;
//allowRetry1=true;
//groupID1=0;

