/**
 *  SoftChalk LessonBuilder
 *  ================ DO NOT EDIT ================
 */

q_item=28;
group_item=8;
tableToggle_array=[];
f_done=[];
feed=[];
q_done=[];
scoreQ=[];
qOrder=[];
qOrder[0]=20;
qOrder[1]=21;
qOrder[2]=22;
qOrder[3]=23;
qOrder[4]=19;
qOrder[5]=3;
qOrder[6]=4;
qOrder[7]=5;
qOrder[8]=26;
qOrder[9]=27;
qOrder[10]=28;
qOrder[11]=24;
qOrder[12]=25;
qOrder[13]=11;
qOrder[14]=13;
num_pages=7;
//groupOrder6=20,21,22,23
//groupName6=GBL

//groupPopupTitle6=
//groupOneAtATime6=true
//groupRandom6=true
//groupPoolSize6=4
//groupRetry6=false
//groupShow6=false
//groupScoreSummary6=false
//groupBorder6=true
//groupOrder2=3,4,5
//groupName2=Examples of Digital Game-based Learning

//groupPopupTitle2=
//groupOneAtATime2=true
//groupRandom2=false
//groupPoolSize2=3
//groupRetry2=true
//groupShow2=false
//groupScoreSummary2=true
//groupBorder2=true
//groupOrder8=26,27,28
//groupName8=Implementation GBL in Classroom Questions

//groupPopupTitle8=
//groupOneAtATime8=true
//groupRandom8=false
//groupPoolSize8=3
//groupRetry8=true
//groupShow8=false
//groupScoreSummary8=true
//groupBorder8=true
//groupOrder7=24,25
//groupName7=Designing and Developing GBL

//groupPopupTitle7=
//groupOneAtATime7=true
//groupRandom7=false
//groupPoolSize7=2
//groupRetry7=true
//groupShow7=false
//groupScoreSummary7=true
//groupBorder7=true
scorm_completed_status=true;

//q_num=20;
inline_feedback20=true;
q_done[20]=false;
q_value20=2;
scoreQ[20]="yes";
mc_items20=2;
//ra_items20=1;
q_type20=2;
theQuestion20="<p>Game-Based Learning (GBL)&nbsp;describes an approach to teaching, where students explore relevant aspect of games in a learning context designed by teachers.</p>";
showCorrect20="no";
showHint20="no";
showFeedbackIndividual20="no";
case_sensitive20="false";
partial_credit20=false;
feedbackRight20="<p>Right! Good job!</p>";
feedbackWrong20="<p>Sorry, incorrect answer.</p>";
feedbackPartial20="Partially correct.";
hint20="";
feedbackIndividual20=[];
right_answers20=[];
right_answers20[0]="true";
answer_choices20=[];
answer_choices20[0]="True";
answer_choices20[1]="False";
tableToggle_array[20]=false;
f_done[20]=false;
feed[20]=false;
//allowRetry20=true;
//groupID20=6;

//q_num=21;
inline_feedback21=true;
q_done[21]=false;
q_value21=2;
scoreQ[21]="yes";
mc_items21=2;
//ra_items21=1;
q_type21=2;
theQuestion21="<p>Ditigal Game-Based Learning started out as an instructional strategy that can be embodied through computer-based applications.</p>";
showCorrect21="no";
showHint21="no";
showFeedbackIndividual21="no";
case_sensitive21="false";
partial_credit21=false;
feedbackRight21="<p>Right! Good job!</p>";
feedbackWrong21="<p>Sorry, incorrect answer.</p>";
feedbackPartial21="Partially correct.";
hint21="";
feedbackIndividual21=[];
right_answers21=[];
right_answers21[0]="true";
answer_choices21=[];
answer_choices21[0]="True";
answer_choices21[1]="False";
tableToggle_array[21]=false;
f_done[21]=false;
feed[21]=false;
//allowRetry21=true;
//groupID21=6;

//q_num=22;
inline_feedback22=true;
q_done[22]=false;
q_value22=2;
scoreQ[22]="yes";
mc_items22=2;
//ra_items22=1;
q_type22=2;
theQuestion22="<p>Digital game-based learning does not refer to using digital video games as learning tools.</p>";
showCorrect22="no";
showHint22="no";
showFeedbackIndividual22="no";
case_sensitive22="false";
partial_credit22=false;
feedbackRight22="<p>Right! Good job!</p>";
feedbackWrong22="<p>Sorry, incorrect answer.</p>";
feedbackPartial22="Partially correct.";
hint22="";
feedbackIndividual22=[];
right_answers22=[];
right_answers22[0]="false";
answer_choices22=[];
answer_choices22[0]="True";
answer_choices22[1]="False";
tableToggle_array[22]=false;
f_done[22]=false;
feed[22]=false;
//allowRetry22=true;
//groupID22=6;

//q_num=23;
inline_feedback23=true;
q_done[23]=false;
q_value23=1;
scoreQ[23]="yes";
mc_items23=2;
//ra_items23=1;
q_type23=2;
theQuestion23="<p>Gamification takes an element of education and replaces it with a game-based element. For instance, a teacher may replace grades with levels or experience points.</p>";
showCorrect23="no";
showHint23="no";
showFeedbackIndividual23="no";
case_sensitive23="false";
partial_credit23=false;
feedbackRight23="<p>Right! Good job!</p>";
feedbackWrong23="<p>Sorry, incorrect answer.</p>";
feedbackPartial23="Partially correct.";
hint23="";
feedbackIndividual23=[];
right_answers23=[];
right_answers23[0]="true";
answer_choices23=[];
answer_choices23[0]="True";
answer_choices23[1]="False";
tableToggle_array[23]=false;
f_done[23]=false;
feed[23]=false;
//allowRetry23=true;
//groupID23=6;

//q_num=19;
inline_feedback19=true;
q_done[19]=false;
q_value19=5;
scoreQ[19]="yes";
mc_items19=0;
//ra_items19=0;
q_type19=8;
theQuestion19="<p>List 5 benifits of using game-based learning in your classroom and explain them.</p>";
showCorrect19="no";
showHint19="no";
showFeedbackIndividual19="no";
case_sensitive19="false";
partial_credit19=false;
feedbackRight19="";
feedbackWrong19="";
feedbackPartial19="Partially correct.";
hint19="";
feedbackIndividual19=[];
right_answers19=[];
right_answers19[0]="";
answer_choices19=[];
answer_choices19[0]="no choices";
tableToggle_array[19]=false;
f_done[19]=false;
feed[19]=false;
//allowRetry19=true;
//groupID19=0;

//q_num=3;
inline_feedback3=true;
q_done[3]=false;
q_value3=10;
scoreQ[3]="yes";
mc_items3=0;
//ra_items3=0;
q_type3=8;
theQuestion3="<p>What game-based learing have you implemented in your classroom before? Explain about what you did.</p>";
showCorrect3="no";
showHint3="no";
showFeedbackIndividual3="no";
case_sensitive3="false";
partial_credit3=false;
feedbackRight3="";
feedbackWrong3="";
feedbackPartial3="Partially correct.";
hint3="";
feedbackIndividual3=[];
right_answers3=[];
right_answers3[0]="";
answer_choices3=[];
answer_choices3[0]="no choices";
tableToggle_array[3]=false;
f_done[3]=false;
feed[3]=false;
//allowRetry3=true;
//groupID3=2;

//q_num=4;
inline_feedback4=true;
q_done[4]=false;
q_value4=3;
scoreQ[4]="yes";
mc_items4=0;
//ra_items4=0;
q_type4=8;
theQuestion4="<p>From the examples you just read what do you think will be most useful for your class?</p>";
showCorrect4="no";
showHint4="no";
showFeedbackIndividual4="no";
case_sensitive4="false";
partial_credit4=false;
feedbackRight4="";
feedbackWrong4="";
feedbackPartial4="Partially correct.";
hint4="";
feedbackIndividual4=[];
right_answers4=[];
right_answers4[0]="";
answer_choices4=[];
answer_choices4[0]="no choices";
tableToggle_array[4]=false;
f_done[4]=false;
feed[4]=false;
//allowRetry4=true;
//groupID4=2;

//q_num=5;
inline_feedback5=true;
q_done[5]=false;
q_value5=5;
scoreQ[5]="yes";
mc_items5=0;
//ra_items5=0;
q_type5=8;
theQuestion5="<p>From the given list of examples of game-based learning, select any one and critique the usage of digital game-based learning in your classroom.</p>";
showCorrect5="no";
showHint5="no";
showFeedbackIndividual5="no";
case_sensitive5="false";
partial_credit5=false;
feedbackRight5="";
feedbackWrong5="";
feedbackPartial5="Partially correct.";
hint5="";
feedbackIndividual5=[];
right_answers5=[];
right_answers5[0]="";
answer_choices5=[];
answer_choices5[0]="no choices";
tableToggle_array[5]=false;
f_done[5]=false;
feed[5]=false;
//allowRetry5=true;
//groupID5=2;

//q_num=26;
inline_feedback26=true;
q_done[26]=false;
q_value26=10;
scoreQ[26]="yes";
mc_items26=0;
//ra_items26=0;
q_type26=8;
theQuestion26="<p>Among all the examples of the digital game-based learning you know so far, list at least 5 digital game-based activities you can implement in your class.</p>";
showCorrect26="no";
showHint26="no";
showFeedbackIndividual26="no";
case_sensitive26="false";
partial_credit26=false;
feedbackRight26="";
feedbackWrong26="";
feedbackPartial26="Partially correct.";
hint26="";
feedbackIndividual26=[];
right_answers26=[];
right_answers26[0]="";
answer_choices26=[];
answer_choices26[0]="no choices";
tableToggle_array[26]=false;
f_done[26]=false;
feed[26]=false;
//allowRetry26=true;
//groupID26=8;

//q_num=27;
inline_feedback27=true;
q_done[27]=false;
q_value27=10;
scoreQ[27]="yes";
mc_items27=0;
//ra_items27=0;
q_type27=8;
theQuestion27="<p>Select minimum one digital game-based learning activity and a digital platform for your classroom implementation.</p>";
showCorrect27="no";
showHint27="no";
showFeedbackIndividual27="no";
case_sensitive27="false";
partial_credit27=false;
feedbackRight27="";
feedbackWrong27="";
feedbackPartial27="Partially correct.";
hint27="";
feedbackIndividual27=[];
right_answers27=[];
right_answers27[0]="";
answer_choices27=[];
answer_choices27[0]="no choices";
tableToggle_array[27]=false;
f_done[27]=false;
feed[27]=false;
//allowRetry27=true;
//groupID27=8;

//q_num=28;
inline_feedback28=true;
q_done[28]=false;
q_value28=10;
scoreQ[28]="yes";
mc_items28=0;
//ra_items28=0;
q_type28=8;
theQuestion28="<p>Make a design draft of the game-based learning activity using a digital platform or software.</p>";
showCorrect28="no";
showHint28="no";
showFeedbackIndividual28="no";
case_sensitive28="false";
partial_credit28=false;
feedbackRight28="";
feedbackWrong28="";
feedbackPartial28="Partially correct.";
hint28="";
feedbackIndividual28=[];
right_answers28=[];
right_answers28[0]="";
answer_choices28=[];
answer_choices28[0]="no choices";
tableToggle_array[28]=false;
f_done[28]=false;
feed[28]=false;
//allowRetry28=true;
//groupID28=8;

//q_num=24;
inline_feedback24=true;
q_done[24]=false;
q_value24=10;
scoreQ[24]="yes";
mc_items24=0;
//ra_items24=0;
q_type24=8;
theQuestion24="<p>Explain the purpose of the game that you are creating and how you plan to implement in in your class.</p>";
showCorrect24="no";
showHint24="no";
showFeedbackIndividual24="no";
case_sensitive24="false";
partial_credit24=false;
feedbackRight24="";
feedbackWrong24="";
feedbackPartial24="Partially correct.";
hint24="";
feedbackIndividual24=[];
right_answers24=[];
right_answers24[0]="";
answer_choices24=[];
answer_choices24[0]="no choices";
tableToggle_array[24]=false;
f_done[24]=false;
feed[24]=false;
//allowRetry24=true;
//groupID24=7;

//q_num=25;
inline_feedback25=true;
q_done[25]=false;
q_value25=10;
scoreQ[25]="yes";
mc_items25=0;
//ra_items25=0;
q_type25=8;
theQuestion25="<p>Plan the introduction of the selected platform and its function to students.</p>";
showCorrect25="no";
showHint25="no";
showFeedbackIndividual25="no";
case_sensitive25="false";
partial_credit25=false;
feedbackRight25="";
feedbackWrong25="";
feedbackPartial25="Partially correct.";
hint25="";
feedbackIndividual25=[];
right_answers25=[];
right_answers25[0]="";
answer_choices25=[];
answer_choices25[0]="no choices";
tableToggle_array[25]=false;
f_done[25]=false;
feed[25]=false;
//allowRetry25=true;
//groupID25=7;

//q_num=11;
inline_feedback11=true;
q_done[11]=false;
q_value11=20;
scoreQ[11]="yes";
mc_items11=0;
//ra_items11=0;
q_type11=8;
theQuestion11="<p>Assemble and finalize the lesson plan for your class using digital game-based learning in the space below. You can do you original work in Microsoft Word then copy-paste it below.</p>";
showCorrect11="no";
showHint11="no";
showFeedbackIndividual11="no";
case_sensitive11="false";
partial_credit11=false;
feedbackRight11="";
feedbackWrong11="";
feedbackPartial11="Partially correct.";
hint11="";
feedbackIndividual11=[];
right_answers11=[];
right_answers11[0]="";
answer_choices11=[];
answer_choices11[0]="no choices";
tableToggle_array[11]=false;
f_done[11]=false;
feed[11]=false;
//allowRetry11=true;
//groupID11=0;

//q_num=13;
inline_feedback13=true;
q_done[13]=false;
q_value13=0;
scoreQ[13]="no";
mc_items13=0;
//ra_items13=0;
q_type13=8;
theQuestion13="<p>Please let us know what your thought of the lesson and how we can further improve it.</p>";
showCorrect13="no";
showHint13="no";
showFeedbackIndividual13="no";
case_sensitive13="false";
partial_credit13=false;
feedbackRight13="";
feedbackWrong13="";
feedbackPartial13="Partially correct.";
hint13="";
feedbackIndividual13=[];
right_answers13=[];
right_answers13[0]="";
answer_choices13=[];
answer_choices13[0]="no choices";
tableToggle_array[13]=false;
f_done[13]=false;
feed[13]=false;
//allowRetry13=true;
//groupID13=0;

