/**
 *  SoftChalk LessonBuilder
 *  ================ DO NOT EDIT ================
 */

q_item=25;
group_item=6;
tableToggle_array=new Array();
f_done=new Array();
feed=new Array();
q_done=new Array();
scoreQ=new Array();
qOrder=new Array();
qOrder[0]=17;
qOrder[1]=18;
qOrder[2]=3;
qOrder[3]=4;
qOrder[4]=5;
qOrder[5]=6;
qOrder[6]=7;
qOrder[7]=8;
qOrder[8]=9;
qOrder[9]=24;
qOrder[10]=10;
qOrder[11]=22;
qOrder[12]=11;
qOrder[13]=21;
qOrder[14]=13;
qOrder[15]=19;
qOrder[16]=25;
num_pages=7;
//groupOrder6=17,18
//groupName6=Self-Care

//groupPopupTitle6=
//groupOneAtATime6=true
//groupRandom6=false
//groupPoolSize6=2
//groupRetry6=false
//groupShow6=true
//groupScoreSummary6=false
//groupBorder6=true
//groupOrder1=6,7
//groupName1=Section A

//groupPopupTitle1=Section A Questions
//groupOneAtATime1=true
//groupRandom1=false
//groupPoolSize1=2
//groupRetry1=false
//groupShow1=false
//groupScoreSummary1=false
//groupBorder1=true
//groupOrder2=8,9,24
//groupName2=Section B Physical Self-care Questions

//groupPopupTitle2=Section B: Physical Self-Care Questions
//groupOneAtATime2=true
//groupRandom2=false
//groupPoolSize2=3
//groupRetry2=false
//groupShow2=false
//groupScoreSummary2=false
//groupBorder2=true
//groupOrder3=10,22
//groupName3=Section C: Emotional Self-Care Questions

//groupPopupTitle3=Section C: Emotional Self-Care Questions
//groupOneAtATime3=true
//groupRandom3=false
//groupPoolSize3=2
//groupRetry3=false
//groupShow3=false
//groupScoreSummary3=false
//groupBorder3=true
//groupOrder4=11,21
//groupName4=Section D: Spiritual Self-Care Questions

//groupPopupTitle4=Section D: Spiritual Self-Care Questions
//groupOneAtATime4=true
//groupRandom4=false
//groupPoolSize4=2
//groupRetry4=false
//groupShow4=false
//groupScoreSummary4=false
//groupBorder4=true
//groupOrder5=13,19
//groupName5=Section E: Final Assessment

//groupPopupTitle5=Section E: Final Assessment
//groupOneAtATime5=true
//groupRandom5=false
//groupPoolSize5=2
//groupRetry5=false
//groupShow5=false
//groupScoreSummary5=false
//groupBorder5=true
scorm_completed_status=true;

//q_num=17;
inline_feedback17=true;
q_done[17]=false;
q_value17=3;
scoreQ[17]="yes";
mc_items17=0;
//ra_items17=0;
q_type17=8;
theQuestion17="<p>&quot;Isn't it Selfish to Put Myself First?&quot;, what are your thoughts for this question. There is no right or wrong answer for this, just write your thoughts on it.</p><p>&nbsp;</p><p>[Tip: Taking care of your needs exists in a balanced, steady place on the middle of a continuum, with intense selfishness on one end, and extreme sacrificing what you need or want for others' sake on the other end. Nurturing oneself is a key factor in being able to maintain strength, resolve, motivation, and inner resources to continue to give to others. In fact, doing too much for others could deprive them of the opportunity to learn how to provide their own self-care.]</p>";
showCorrect17="no";
showHint17="no";
showFeedbackIndividual17="no";
case_sensitive17="false";
partial_credit17=false;
feedbackRight17="";
feedbackWrong17="";
feedbackPartial17="Partially correct.";
hint17="";
feedbackIndividual17=new Array(0);
right_answers17=new Array(1);
right_answers17[0]="";
answer_choices17=new Array(1);
answer_choices17[0]="no choices";
tableToggle_array[17]=false;
f_done[17]=false;
feed[17]=false;
//allowRetry17=true;
//groupID17=6;

//q_num=18;
inline_feedback18=true;
q_done[18]=false;
q_value18=3;
scoreQ[18]="yes";
mc_items18=0;
//ra_items18=0;
q_type18=8;
theQuestion18="<p>Reflect on the different situations you have just learnt about. Now think of any other situation you might have faced and write about what you think you should in those situations.</p>";
showCorrect18="no";
showHint18="no";
showFeedbackIndividual18="no";
case_sensitive18="false";
partial_credit18=false;
feedbackRight18="";
feedbackWrong18="";
feedbackPartial18="Partially correct.";
hint18="";
feedbackIndividual18=new Array(0);
right_answers18=new Array(1);
right_answers18[0]="";
answer_choices18=new Array(1);
answer_choices18[0]="no choices";
tableToggle_array[18]=false;
f_done[18]=false;
feed[18]=false;
//allowRetry18=true;
//groupID18=6;

//q_num=3;
inline_feedback3=true;
q_done[3]=false;
q_value3=3;
scoreQ[3]="yes";
mc_items3=0;
//ra_items3=0;
q_type3=8;
theQuestion3="<p>How much of physical self-care do you do? There were several points listed on the 'how to' section of physical self-care. Do you think some of them could help you to take care for yourself? If so, make a list of your three favorite points that may fit in your own life then explain how you plan to implement them in your life.</p><p>[The feedback for this question is not instant. The instructor will provide feedback upon review which might take sometime.]</p>";
showCorrect3="no";
showHint3="no";
showFeedbackIndividual3="no";
case_sensitive3="false";
partial_credit3=false;
feedbackRight3="";
feedbackWrong3="";
feedbackPartial3="Partially correct.";
hint3="";
feedbackIndividual3=new Array(0);
right_answers3=new Array(1);
right_answers3[0]="";
answer_choices3=new Array(1);
answer_choices3[0]="no choices";
tableToggle_array[3]=false;
f_done[3]=false;
feed[3]=false;
//allowRetry3=true;
//groupID3=0;

//q_num=4;
inline_feedback4=true;
q_done[4]=false;
q_value4=3;
scoreQ[4]="yes";
mc_items4=0;
//ra_items4=0;
q_type4=8;
theQuestion4="<p>How do you take care of your emotional needs? There were several points listed on the 'how to' section of emotional self-care. Do you think some of them could help you to take care for yourself? If so, make a list of your three favorite points that may fit in your own life then explain how you plan to implement them in your life.</p><p>[The feedback for this question is not instant. The instructor will provide feedback upon review which might take sometime.]</p>";
showCorrect4="no";
showHint4="no";
showFeedbackIndividual4="no";
case_sensitive4="false";
partial_credit4=false;
feedbackRight4="";
feedbackWrong4="";
feedbackPartial4="Partially correct.";
hint4="";
feedbackIndividual4=new Array(0);
right_answers4=new Array(1);
right_answers4[0]="";
answer_choices4=new Array(1);
answer_choices4[0]="no choices";
tableToggle_array[4]=false;
f_done[4]=false;
feed[4]=false;
//allowRetry4=true;
//groupID4=0;

//q_num=5;
inline_feedback5=true;
q_done[5]=false;
q_value5=3;
scoreQ[5]="yes";
mc_items5=0;
//ra_items5=0;
q_type5=8;
theQuestion5="<p>What is spiritual self-care for you? There were several points listed on the 'how to' section of spiritual self-care. Do you think some of them could help you to take care for yourself? If so, make a list of your three favorite points that may fit in your own life, then explain how you plan to implement them in your life.</p><p>[The feedback for this question is not instant. The instructor will provide feedback upon review which might take sometime.]</p>";
showCorrect5="no";
showHint5="no";
showFeedbackIndividual5="no";
case_sensitive5="false";
partial_credit5=false;
feedbackRight5="";
feedbackWrong5="";
feedbackPartial5="Partially correct.";
hint5="";
feedbackIndividual5=new Array(0);
right_answers5=new Array(1);
right_answers5[0]="";
answer_choices5=new Array(1);
answer_choices5[0]="no choices";
tableToggle_array[5]=false;
f_done[5]=false;
feed[5]=false;
//allowRetry5=true;
//groupID5=0;

//q_num=6;
inline_feedback6=true;
q_done[6]=false;
q_value6=3;
scoreQ[6]="yes";
mc_items6=3;
//ra_items6=1;
q_type6=1;
theQuestion6="<p>Choose the best answer. The most important thing you have to do is....</p>";
showCorrect6="no";
showHint6="no";
showFeedbackIndividual6="yes";
case_sensitive6="false";
partial_credit6=false;
feedbackRight6="<p>Right! Good job!</p>";
feedbackWrong6="<p>Sorry, incorrect answer.</p>";
feedbackPartial6="Partially correct.";
hint6="";
feedbackIndividual6=new Array(3);
feedbackIndividual6[0]="";
feedbackIndividual6[1]="";
feedbackIndividual6[2]="";
right_answers6=new Array(1);
right_answers6[0]="b";
answer_choices6=new Array(3);
answer_choices6[0]="<p>focus only in your job.</p>";
answer_choices6[1]="<p>work on yourself. Fill yourself up and keep yourself full.</p>";
answer_choices6[2]="<p>work for others.</p>";
tableToggle_array[6]=false;
f_done[6]=false;
feed[6]=false;
//allowRetry6=true;
//groupID6=1;

//q_num=7;
inline_feedback7=true;
q_done[7]=false;
q_value7=3;
scoreQ[7]="yes";
mc_items7=2;
//ra_items7=1;
q_type7=2;
theQuestion7="<p>You should not be afraid of honoring yourself.</p>";
showCorrect7="no";
showHint7="no";
showFeedbackIndividual7="no";
case_sensitive7="false";
partial_credit7=false;
feedbackRight7="<p>Right! Good job!</p>";
feedbackWrong7="<p>Sorry, incorrect answer.</p>";
feedbackPartial7="Partially correct.";
hint7="";
feedbackIndividual7=new Array(0);
right_answers7=new Array(1);
right_answers7[0]="true";
answer_choices7=new Array(2);
answer_choices7[0]="True";
answer_choices7[1]="False";
tableToggle_array[7]=false;
f_done[7]=false;
feed[7]=false;
//allowRetry7=true;
//groupID7=1;

//q_num=8;
inline_feedback8=true;
q_done[8]=false;
q_value8=3;
scoreQ[8]="yes";
mc_items8=4;
//ra_items8=1;
q_type8=1;
theQuestion8="<p>How to eat healthy foods?</p>";
showCorrect8="no";
showHint8="no";
showFeedbackIndividual8="yes";
case_sensitive8="false";
partial_credit8=false;
feedbackRight8="<p>Right! Good job!</p>";
feedbackWrong8="<p>Sorry, incorrect answer.</p>";
feedbackPartial8="Partially correct.";
hint8="";
feedbackIndividual8=new Array(4);
feedbackIndividual8[0]="";
feedbackIndividual8[1]="";
feedbackIndividual8[2]="";
feedbackIndividual8[3]="";
right_answers8=new Array(1);
right_answers8[0]="a";
answer_choices8=new Array(4);
answer_choices8[0]="<p>Eat whole grains, more dark green vegetables and variety of fresh or frozen fruit.</p><p>&nbsp;</p>";
answer_choices8[1]="<p>Try only single type of lean proteins.</p>";
answer_choices8[2]="<p>Eat only snacks.</p>";
answer_choices8[3]="<p>Eat once a day only.</p>";
tableToggle_array[8]=false;
f_done[8]=false;
feed[8]=false;
//allowRetry8=true;
//groupID8=2;

//q_num=9;
inline_feedback9=true;
q_done[9]=false;
q_value9=3;
scoreQ[9]="yes";
mc_items9=5;
//ra_items9=1;
q_type9=3;
theQuestion9="<p>How would you monitor your physical health?</p>";
showCorrect9="no";
showHint9="no";
showFeedbackIndividual9="yes";
case_sensitive9="false";
partial_credit9=false;
feedbackRight9="<p>Right! Good job!</p>";
feedbackWrong9="<p>Sorry, incorrect answer.</p>";
feedbackPartial9="<p>Partially correct.</p>";
hint9="";
feedbackIndividual9=new Array(5);
feedbackIndividual9[0]="";
feedbackIndividual9[1]="";
feedbackIndividual9[2]="";
feedbackIndividual9[3]="";
feedbackIndividual9[4]="";
right_answers9=new Array(1);
right_answers9[0]="a,c,e";
answer_choices9=new Array(5);
answer_choices9[0]="<p>Take time to appreciate every amazing thing your body does</p><p>&nbsp;</p>";
answer_choices9[1]="<p>Work even though you are sick</p>";
answer_choices9[2]="<p>Schedule regular appointments with your doctor</p>";
answer_choices9[3]="<p>Do not take medicine when you are sick</p>";
answer_choices9[4]="<p>Pay attention to body sensations and notice spots of attention</p>";
tableToggle_array[9]=false;
f_done[9]=false;
feed[9]=false;
//allowRetry9=true;
//groupID9=2;

//q_num=24;
inline_feedback24=true;
q_done[24]=false;
q_value24=3;
scoreQ[24]="yes";
mc_items24=0;
//ra_items24=0;
q_type24=8;
theQuestion24="<p>How often do you stretch? What kind of movement makes you truly happy? How regularly do you do it?</p>";
showCorrect24="no";
showHint24="no";
showFeedbackIndividual24="no";
case_sensitive24="false";
partial_credit24=false;
feedbackRight24="";
feedbackWrong24="";
feedbackPartial24="Partially correct.";
hint24="";
feedbackIndividual24=new Array(0);
right_answers24=new Array(1);
right_answers24[0]="";
answer_choices24=new Array(1);
answer_choices24[0]="no choices";
tableToggle_array[24]=false;
f_done[24]=false;
feed[24]=false;
//allowRetry24=true;
//groupID24=2;

//q_num=10;
inline_feedback10=true;
q_done[10]=false;
q_value10=1;
scoreQ[10]="yes";
mc_items10=2;
//ra_items10=1;
q_type10=2;
theQuestion10="<p>Emotional self-care is not as important as physical self-care.</p>";
showCorrect10="no";
showHint10="no";
showFeedbackIndividual10="no";
case_sensitive10="false";
partial_credit10=false;
feedbackRight10="<p>Right! Good job!</p>";
feedbackWrong10="<p>Sorry, incorrect answer.</p>";
feedbackPartial10="Partially correct.";
hint10="";
feedbackIndividual10=new Array(0);
right_answers10=new Array(1);
right_answers10[0]="false";
answer_choices10=new Array(2);
answer_choices10[0]="True";
answer_choices10[1]="False";
tableToggle_array[10]=false;
f_done[10]=false;
feed[10]=false;
//allowRetry10=true;
//groupID10=3;

//q_num=22;
inline_feedback22=true;
q_done[22]=false;
q_value22=3;
scoreQ[22]="yes";
mc_items22=0;
//ra_items22=0;
q_type22=8;
theQuestion22="<p>Tina is an undergrad, she schedules every moment of every day except for the five hours she sleeps each night. She has been told that having an impressive resume would allow her to compete with other journalists once she graduats, so she juggles an overwhelming number of class credits, a job as editor-in-chief of the school's magazine, a role as a resident assistant, and an internship. This mountain of responsibilities leaves her little time to care for her emotional health.</p><p>What suggestions do you have for her? Give 4-5 tips that she can implement in her life for her emotional self-care.</p>";
showCorrect22="no";
showHint22="no";
showFeedbackIndividual22="no";
case_sensitive22="false";
partial_credit22=false;
feedbackRight22="";
feedbackWrong22="";
feedbackPartial22="Partially correct.";
hint22="";
feedbackIndividual22=new Array(0);
right_answers22=new Array(1);
right_answers22[0]="";
answer_choices22=new Array(1);
answer_choices22[0]="no choices";
tableToggle_array[22]=false;
f_done[22]=false;
feed[22]=false;
//allowRetry22=true;
//groupID22=3;

//q_num=11;
inline_feedback11=true;
q_done[11]=false;
q_value11=1;
scoreQ[11]="yes";
mc_items11=2;
//ra_items11=1;
q_type11=2;
theQuestion11="<p>Spiritual Self-Care is as important as physical self-care.</p>";
showCorrect11="no";
showHint11="no";
showFeedbackIndividual11="no";
case_sensitive11="false";
partial_credit11=false;
feedbackRight11="<p>Right! Good job!</p>";
feedbackWrong11="<p>Sorry, incorrect answer.</p>";
feedbackPartial11="Partially correct.";
hint11="";
feedbackIndividual11=new Array(0);
right_answers11=new Array(1);
right_answers11[0]="true";
answer_choices11=new Array(2);
answer_choices11[0]="True";
answer_choices11[1]="False";
tableToggle_array[11]=false;
f_done[11]=false;
feed[11]=false;
//allowRetry11=true;
//groupID11=4;

//q_num=21;
inline_feedback21=true;
q_done[21]=false;
q_value21=3;
scoreQ[21]="yes";
mc_items21=5;
//ra_items21=1;
q_type21=3;
theQuestion21="<p>Which of the following can be considered as spiritual self-care?</p>";
showCorrect21="no";
showHint21="no";
showFeedbackIndividual21="yes";
case_sensitive21="false";
partial_credit21=false;
feedbackRight21="<p>Right! Good job!</p>";
feedbackWrong21="<p>Sorry, incorrect answer.</p>";
feedbackPartial21="<p>Partially correct.</p>";
hint21="";
feedbackIndividual21=new Array(5);
feedbackIndividual21[0]="";
feedbackIndividual21[1]="";
feedbackIndividual21[2]="";
feedbackIndividual21[3]="";
feedbackIndividual21[4]="";
right_answers21=new Array(1);
right_answers21[0]="a,b,c";
answer_choices21=new Array(5);
answer_choices21[0]="<p>Engage in reflective practices like meditation.</p><p>&nbsp;</p>";
answer_choices21[1]="<p>Go on walks.</p>";
answer_choices21[2]="<p>Go to church/mosque/temple.</p>";
answer_choices21[3]="<p>Pressuring yourself</p>";
answer_choices21[4]="<p>Go for medical check-up</p>";
tableToggle_array[21]=false;
f_done[21]=false;
feed[21]=false;
//allowRetry21=true;
//groupID21=4;

//q_num=13;
inline_feedback13=true;
q_done[13]=false;
q_value13=3;
scoreQ[13]="yes";
mc_items13=3;
//ra_items13=3;
q_type13=5;
theQuestion13="<p>Match the items.</p>";
showCorrect13="no";
showHint13="no";
showFeedbackIndividual13="no";
case_sensitive13="false";
partial_credit13=false;
feedbackRight13="<p>Right! Good job!</p>";
feedbackWrong13="<p>Sorry, incorrect answer.</p>";
feedbackPartial13="<p>Partially correct.</p>";
hint13="";
feedbackIndividual13=new Array(0);
right_answers13=new Array(3);
right_answers13[0]="1";
right_answers13[1]="0";
right_answers13[2]="2";
answer_choices13=new Array(3);
answer_choices13[0]="<p>This self-care involves activities that improve your physical health, including diet and exercise.</p>";
answer_choices13[1]="<p>This self-care involves practices that maintain your mental strength and emotional health.</p>";
answer_choices13[2]="<p>This self-care involves practices that exercise your mind and soul.</p>";
tableToggle_array[13]=false;
f_done[13]=false;
feed[13]=false;
//items_to_match13[0]="<p>Emotional Self-Care</p>";
//items_to_match13[1]="<p>Physical Self-Care</p>";
//items_to_match13[2]="<p>Spiritual Self-Care</p>";
//allowRetry13=true;
//groupID13=5;

//q_num=19;
inline_feedback19=true;
q_done[19]=false;
q_value19=3;
scoreQ[19]="yes";
mc_items19=0;
//ra_items19=0;
q_type19=8;
theQuestion19="<p>Brinda has started her last semester of college. She ended up taking heavy course load, and started having panic attacks. She is overloaded with stress, and anxiety, and fear. What advice would you give her?</p>";
showCorrect19="no";
showHint19="no";
showFeedbackIndividual19="no";
case_sensitive19="false";
partial_credit19=false;
feedbackRight19="";
feedbackWrong19="";
feedbackPartial19="Partially correct.";
hint19="";
feedbackIndividual19=new Array(0);
right_answers19=new Array(1);
right_answers19[0]="";
answer_choices19=new Array(1);
answer_choices19[0]="no choices";
tableToggle_array[19]=false;
f_done[19]=false;
feed[19]=false;
//allowRetry19=true;
//groupID19=5;

//q_num=25;
inline_feedback25=true;
q_done[25]=false;
q_value25=0;
scoreQ[25]="no";
mc_items25=0;
//ra_items25=0;
q_type25=8;
theQuestion25="<p>Please leave the feedback about the course. You may include the answers on following questions:</p><p>What did you like the most? What are the areas for improvement? What would you add to the course? etc.</p>";
showCorrect25="no";
showHint25="no";
showFeedbackIndividual25="no";
case_sensitive25="false";
partial_credit25=false;
feedbackRight25="";
feedbackWrong25="";
feedbackPartial25="Partially correct.";
hint25="";
feedbackIndividual25=new Array(0);
right_answers25=new Array(1);
right_answers25[0]="";
answer_choices25=new Array(1);
answer_choices25[0]="no choices";
tableToggle_array[25]=false;
f_done[25]=false;
feed[25]=false;
//allowRetry25=true;
//groupID25=0;

