/**
 *  SoftChalk LessonBuilder
 *  ================ DO NOT EDIT ================
 */

var groupFinished = [];
var currentQPNum = [];
var quizGroupSize = [];
var firstDisplayed = [];
function randomizeQp(myArray) {
var i = myArray.length;
  while ( --i ) {
    var j = Math.floor(Math.random() * (i + 1));
    var tempi = myArray[i];
    var tempj = myArray[j];
    myArray[i] = tempj;
    myArray[j] = tempi;
  }
}


groupFinished[2] = false;
firstDisplayed[2] = false;
currentQPNum[2] = 1;
var groupQpArray2 = [];
var groupQpStateArray2 = [];
var qpNumbersArray2 = [];
qpNumbersArray2[0] = 1;
qpNumbersArray2[1] = 2;
qpNumbersArray2[2] = 3;
randomizeQp(qpNumbersArray2);
quizGroupSize[2] = 3;
groupQpArray2[1]='<div id="quizpopper4"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f4"><fieldset><div class="qp-the-question"><legend><p>Before creating any account you do not have to think about the time and commitment you need to make, you can just start by creating an account.</p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q4" value="true" id="q4a"></div><div class="qp-t-f-cell-right"><label for="q4a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q4" value="false" id="q4b"></div><div class="qp-t-f-cell-right"><label for="q4b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done4"></div><div class="collapse qpqfeedback2" id="feed4"></div></div></div>';
groupQpArray2[2]='<div id="quizpopper5"><div class="qpqvalue">Value: 8</div><div class="qpq"><form class="qp-form" name="f5"><fieldset><div class="qp-the-question"><legend><p>Put the items in the correct order.</p></legend></div><div class="hideqpstuff">Below is a sequence of events. Place them in the order they should occur, number 1 being the first item. Select the step number from the drop down next to each item.</div><div class="qpindent"><div class="hideqpstuff">Items to order:<div>1. <p>Secure approval from your Vice President or Cabinet Member.</p></div><div>2. <p>Think about the commitment that needs to be made.</p></div><div>3. <p>Create a plan for the account.</p></div><div>4. <p>Submit the Social Media Registration Form.</p></div></div><div class="qp-table"><div class="qp-row"><div class="qp-ordering-cell-left"><label for="q5_1"><p>Secure approval from your Vice President or Cabinet Member.</p></label></div><div class="qp-ordering-cell-right"><select class="form-control qp-select" name="q5_1" id="q5_1"><option>1</option><option>2</option><option>3</option><option>4</option></select></div></div><div class="qp-row"><div class="qp-ordering-cell-left"><label for="q5_2"><p>Think about the commitment that needs to be made.</p></label></div><div class="qp-ordering-cell-right"><select class="form-control qp-select" name="q5_2" id="q5_2"><option>1</option><option>2</option><option>3</option><option>4</option></select></div></div><div class="qp-row"><div class="qp-ordering-cell-left"><label for="q5_3"><p>Create a plan for the account.</p></label></div><div class="qp-ordering-cell-right"><select class="form-control qp-select" name="q5_3" id="q5_3"><option>1</option><option>2</option><option>3</option><option>4</option></select></div></div><div class="qp-row"><div class="qp-ordering-cell-left"><label for="q5_4"><p>Submit the Social Media Registration Form.</p></label></div><div class="qp-ordering-cell-right"><select class="form-control qp-select" name="q5_4" id="q5_4"><option>1</option><option>2</option><option>3</option><option>4</option></select></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done5"></div><div class="collapse qpqfeedback2" id="feed5"></div></div></div>';
groupQpArray2[3]='<div id="quizpopper12"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f12"><fieldset><div class="qp-the-question"><legend><p>The maintenance of social media account(s) is not time-consuming, so you do not have to think about the time and commitment.</p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q12" value="true" id="q12a"></div><div class="qp-t-f-cell-right"><label for="q12a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q12" value="false" id="q12b"></div><div class="qp-t-f-cell-right"><label for="q12b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done12"></div><div class="collapse qpqfeedback2" id="feed12"></div></div></div>';


groupFinished[3] = false;
firstDisplayed[3] = false;
currentQPNum[3] = 1;
var groupQpArray3 = [];
var groupQpStateArray3 = [];
var qpNumbersArray3 = [];
qpNumbersArray3[0] = 1;
qpNumbersArray3[1] = 2;
qpNumbersArray3[2] = 3;
qpNumbersArray3[3] = 4;
randomizeQp(qpNumbersArray3);
quizGroupSize[3] = 4;
groupQpArray3[1]='<div id="quizpopper6"><div class="qpqvalue">Value: 16</div><div class="qpq"><form class="qp-form" name="f6"><fieldset><div class="qp-the-question"><legend><p>For moderating accounts in social media, do not delete comments as a way of resolving the issue. But, you can delete, hide or block comments that are:</p></legend></div><div class="qpindent"><div class="qp-m-answer-instruction">[mark all correct answers]</div><div class="qp-table"><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q6" value="a" id="q6a"></div><div class="qp-m-answer-cell-middle">a.</div><div class="qp-m-answer-cell-right"><p>incite violence or otherwise discriminatory or harassing.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q6" value="b" id="q6b"></div><div class="qp-m-answer-cell-middle">b.</div><div class="qp-m-answer-cell-right"><p>repeatedly irrelevant to the university.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q6" value="c" id="q6c"></div><div class="qp-m-answer-cell-middle">c.</div><div class="qp-m-answer-cell-right"><p>are obscene or defamatory.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q6" value="d" id="q6d"></div><div class="qp-m-answer-cell-middle">d.</div><div class="qp-m-answer-cell-right"><p>contradictory to University Policies</p></div></label></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done6"></div><div class="collapse qpqfeedback2" id="feed6"></div></div></div>';
groupQpArray3[2]='<div id="quizpopper7"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f7"><fieldset><div class="qp-the-question"><legend><p>Inactive accounts reflect poorly on the university. It can also be confusing if a department or organization has both active and inactive accounts. When people are searching for you on social media, they may only find the inactive account(s).</p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q7" value="true" id="q7a"></div><div class="qp-t-f-cell-right"><label for="q7a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q7" value="false" id="q7b"></div><div class="qp-t-f-cell-right"><label for="q7b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done7"></div><div class="collapse qpqfeedback2" id="feed7"></div></div></div>';
groupQpArray3[3]='<div id="quizpopper8"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f8"><fieldset><div class="qp-the-question"><legend><p>Securing proper permissions before using photos, videos, and music with your posts is not necessary. &nbsp;</p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q8" value="true" id="q8a"></div><div class="qp-t-f-cell-right"><label for="q8a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q8" value="false" id="q8b"></div><div class="qp-t-f-cell-right"><label for="q8b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done8"></div><div class="collapse qpqfeedback2" id="feed8"></div></div></div>';
groupQpArray3[4]='<div id="quizpopper13"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f13"><fieldset><div class="qp-the-question"><legend><p>All new or old social media accounts affiliated with Indiana State University must be registered. As part of the registration process, it is required that you provide the name, phone number and email address for the account manager and a backup manager(s), as well as account information.</p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q13" value="true" id="q13a"></div><div class="qp-t-f-cell-right"><label for="q13a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q13" value="false" id="q13b"></div><div class="qp-t-f-cell-right"><label for="q13b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done13"></div><div class="collapse qpqfeedback2" id="feed13"></div></div></div>';


groupFinished[4] = false;
firstDisplayed[4] = false;
currentQPNum[4] = 1;
var groupQpArray4 = [];
var groupQpStateArray4 = [];
var qpNumbersArray4 = [];
qpNumbersArray4[0] = 1;
qpNumbersArray4[1] = 2;
qpNumbersArray4[2] = 3;
randomizeQp(qpNumbersArray4);
quizGroupSize[4] = 3;
groupQpArray4[1]='<div id="quizpopper14"><div class="qpqvalue">Value: 16</div><div class="qpq"><form class="qp-form" name="f14"><fieldset><div class="qp-the-question"><legend><p>Keeping social media accessible means:</p></legend></div><div class="qpindent"><div class="qp-m-answer-instruction">[mark all correct answers]</div><div class="qp-table"><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q14" value="a" id="q14a"></div><div class="qp-m-answer-cell-middle">a.</div><div class="qp-m-answer-cell-right"><p>presenting information in the clearest ways possible.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q14" value="b" id="q14b"></div><div class="qp-m-answer-cell-middle">b.</div><div class="qp-m-answer-cell-right"><p>learning from your followers.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q14" value="c" id="q14c"></div><div class="qp-m-answer-cell-middle">c.</div><div class="qp-m-answer-cell-right"><p>ensure that posts are not inclusive to all individuals.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q14" value="d" id="q14d"></div><div class="qp-m-answer-cell-middle">d.</div><div class="qp-m-answer-cell-right"><p>developed so that people with disabilities can use it.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q14" value="e" id="q14e"></div><div class="qp-m-answer-cell-middle">e.</div><div class="qp-m-answer-cell-right"><p>recognizing exclusion.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q14" value="f" id="q14f"></div><div class="qp-m-answer-cell-middle">f.</div><div class="qp-m-answer-cell-right"><p>closed captioning must be available.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q14" value="g" id="q14g"></div><div class="qp-m-answer-cell-middle">g.</div><div class="qp-m-answer-cell-right"><p>avoiding long strings of emojis.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q14" value="h" id="q14h"></div><div class="qp-m-answer-cell-middle">h.</div><div class="qp-m-answer-cell-right"><p>alternating each word with an emoji.</p></div></label></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done14"></div><div class="collapse qpqfeedback2" id="feed14"></div></div></div>';
groupQpArray4[2]='<div id="quizpopper15"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f15"><fieldset><div class="qp-the-question"><legend><p>To ensure that your social media texts are accessible for people with disabilities:</p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-choice-cell-left"><input type="radio" name="q15" value="a" id="q15a"></div><div class="qp-m-choice-cell-middle">a.</div><div class="qp-m-choice-cell-right"><p>It needs to have accurate captions.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-choice-cell-left"><input type="radio" name="q15" value="b" id="q15b"></div><div class="qp-m-choice-cell-middle">b.</div><div class="qp-m-choice-cell-right"><p>It needs to be free of acronyms, jargons and abbreviations.</p></div></label></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done15"></div><div class="collapse qpqfeedback2" id="feed15"></div></div></div>';
groupQpArray4[3]='<div id="quizpopper16"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f16"><fieldset><div class="qp-the-question"><legend><p>To make your social media photo accessible, an alternate text needs to be added for the image if the platform supports it, or the photo description should be included at the end of the post if the platform does not support alt text.</p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q16" value="true" id="q16a"></div><div class="qp-t-f-cell-right"><label for="q16a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q16" value="false" id="q16b"></div><div class="qp-t-f-cell-right"><label for="q16b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done16"></div><div class="collapse qpqfeedback2" id="feed16"></div></div></div>';


groupFinished[5] = false;
firstDisplayed[5] = false;
currentQPNum[5] = 1;
var groupQpArray5 = [];
var groupQpStateArray5 = [];
var qpNumbersArray5 = [];
qpNumbersArray5[0] = 1;
qpNumbersArray5[1] = 2;
qpNumbersArray5[2] = 3;
qpNumbersArray5[3] = 4;
qpNumbersArray5[4] = 5;
randomizeQp(qpNumbersArray5);
quizGroupSize[5] = 5;
groupQpArray5[1]='<div id="quizpopper19"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f19"><fieldset><div class="qp-the-question"><legend><p>The given image below is a correct form to post in social media.</p><p><img src="Incorrect form.PNG" width="328" height="422" class="resizable" metadata="obj24" alt="Image that has texts written over it and there are some texts that cannot be read." style="margin-left: 20px; margin-right: 20px; border: 0"></p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q19" value="true" id="q19a"></div><div class="qp-t-f-cell-right"><label for="q19a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q19" value="false" id="q19b"></div><div class="qp-t-f-cell-right"><label for="q19b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done19"></div><div class="collapse qpqfeedback2" id="feed19"></div></div></div>';
groupQpArray5[2]='<div id="quizpopper20"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f20"><fieldset><div class="qp-the-question"><legend><p>Which of the image along with its texts below is the best to post in social media?</p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-choice-cell-left"><input type="radio" name="q20" value="a" id="q20a"></div><div class="qp-m-choice-cell-middle">a.</div><div class="qp-m-choice-cell-right"><p><img src="Correct form 2.PNG" width="622" height="624" class="resizable" metadata="obj25" alt="Earth day image with texts written and the hastag is at the end" style="margin-left: 20px; margin-right: 20px; border: 0"></p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-choice-cell-left"><input type="radio" name="q20" value="b" id="q20b"></div><div class="qp-m-choice-cell-middle">b.</div><div class="qp-m-choice-cell-right"><p><img src="Incorrect form 1.PNG" width="623" height="624" class="resizable" metadata="obj26" alt="Earth day image with texts written and the hastags are in between sentences." style="margin-left: 20px; margin-right: 20px; border: 0"></p></div></label></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done20"></div><div class="collapse qpqfeedback2" id="feed20"></div></div></div>';
groupQpArray5[3]='<div id="quizpopper21"><div class="qpqvalue">Value: 4</div><div class="qpq"><form class="qp-form" name="f21"><fieldset><div class="qp-the-question"><legend><p>Match the items.</p></legend></div><div class="hideqpstuff">The task is to match the lettered items with the correct numbered items. Appearing below is a list of lettered items. Following that is a list of numbered items. Each numbered item is followed by a drop-down. Select the letter in the drop down that best matches the numbered item with the lettered alternatives.</div><div class="qpindent"><div class="qp-matching-item-container"><div class="qp-table"><div class="qp-row"><div class="qp-match-cell-left">a.</div><div class="qp-match-cell-middle"><p><img src="not 3.PNG" width="661" height="185" class="resizable" metadata="obj30" alt="Image post that has symbols and different styles in the sentence." style="margin-left: 20px; margin-right: 20px; border: 0"></p></div></div><div class="qp-row"><div class="qp-match-cell-left">b.</div><div class="qp-match-cell-middle"><p><img src="Correct form.PNG" width="301" height="331" class="resizable" metadata="obj28" alt="This is a news image that has texts and images displayed clearly." style="margin-left: 20px; margin-right: 20px; border: 0"></p></div></div></div></div><div class="qp-table"><div class="qp-row"><div class="qp-match-cell-left">1.</div><div class="qp-match-cell-middle"><label for="q21_1"><p>Correct</p></label></div><div class="qp-match-cell-right"><select class="form-control qp-select" name="q21_1" id="q21_1"><option>a</option><option>b</option></select></div></div><div class="qp-row"><div class="qp-match-cell-left">2.</div><div class="qp-match-cell-middle"><label for="q21_2"><p>Incorrect</p></label></div><div class="qp-match-cell-right"><select class="form-control qp-select" name="q21_2" id="q21_2"><option>a</option><option>b</option></select></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done21"></div><div class="collapse qpqfeedback2" id="feed21"></div></div></div>';
groupQpArray5[4]='<div id="quizpopper22"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f22"><fieldset><div class="qp-the-question"><legend><p>This post below is a correct form of posting in social media.</p><p><img src="Correct form 3.jpg" width="596" height="715" class="resizable" metadata="obj31" alt="This post has text with image correctly explained and has hastags after the end of the sentence. The text in the image os easy to read." style="margin-left: 20px; margin-right: 20px; border: 0"></p></legend></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q22" value="true" id="q22a"></div><div class="qp-t-f-cell-right"><label for="q22a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q22" value="false" id="q22b"></div><div class="qp-t-f-cell-right"><label for="q22b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done22"></div><div class="collapse qpqfeedback2" id="feed22"></div></div></div>';
groupQpArray5[5]='<div id="quizpopper23"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f23"><fieldset><div class="qp-the-question"><legend><p>Look at the post below and select all that apply.</p><p><img src="Correct form 1.1.PNG" width="741" height="621" class="resizable" metadata="obj34" alt="Business workshop post with its details in readable format" style="margin-left: 20px; margin-right: 20px; border: 0"></p></legend></div><div class="qpindent"><div class="qp-m-answer-instruction">[mark all correct answers]</div><div class="qp-table"><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q23" value="a" id="q23a"></div><div class="qp-m-answer-cell-middle">a.</div><div class="qp-m-answer-cell-right"><p>The texts are easy to read.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q23" value="b" id="q23b"></div><div class="qp-m-answer-cell-middle">b.</div><div class="qp-m-answer-cell-right"><p>The image does not match the text.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q23" value="c" id="q23c"></div><div class="qp-m-answer-cell-middle">c.</div><div class="qp-m-answer-cell-right"><p>The post needs more information.</p></div></label></div><div class="qp-row"><label style="margin-bottom:0;"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q23" value="d" id="q23d"></div><div class="qp-m-answer-cell-middle">d.</div><div class="qp-m-answer-cell-right"><p>The post states its purpose clearly.</p></div></label></div></div></div></fieldset></form><div class="collapse qpqfeedback" id="f_done23"></div><div class="collapse qpqfeedback2" id="feed23"></div></div></div>';

