/**
 *  SoftChalk LessonBuilder
 *  ================ DO NOT EDIT ================
 */

var groupFinished = new Array();
var currentQPNum = new Array();
var quizGroupSize = new Array();
var firstDisplayed = new Array();
function randomizeQp(myArray) {
var i = myArray.length;
  while ( --i ) {
    var j = Math.floor(Math.random() * (i + 1));
    var tempi = myArray[i];
    var tempj = myArray[j];
    myArray[i] = tempj;
    myArray[j] = tempi;
  }
}


groupFinished[5] = false;
firstDisplayed[5] = false;
currentQPNum[5] = 1;
var groupQpArray5 = new Array();
var groupQpStateArray5 = new Array();
var qpNumbersArray5 = new Array();
qpNumbersArray5[0] = 1;
qpNumbersArray5[1] = 2;
qpNumbersArray5[2] = 3;
quizGroupSize[5] = 3;
groupQpArray5[1]='<div id="quizpopper20"><div class="qpq"><form class="qp-form" name="f20"><div class="qp-the-question"><p>When the attacker grabs, first thing you are going to do is drop your center of gravity way forward and become very difficult to lift. Then you are going to hit him.</p></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q20" value="true" id="q20a"></div><div class="qp-t-f-cell-right"><label for="q20a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q20" value="false" id="q20b"></div><div class="qp-t-f-cell-right"><label for="q20b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done20"></div><div class="collapse qpqfeedback2" id="feed20"></div></div></div>';
groupQpArray5[2]='<div id="quizpopper22"><div class="qpq"><form class="qp-form" name="f22"><div class="qp-the-question"><p>When you get pulled from the rear by your hair, your automatic reaction for the pull should be to cover your head, so your hands are going to come up to protect your face. Then what are you going to do?</p></div><div class="qpindent"><div class="qp-m-answer-instruction">[mark all correct answers]</div><div class="qp-table"><div class="qp-row"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q22" value="a" id="q22a"></div><div class="qp-m-answer-cell-middle">a.</div><div class="qp-m-answer-cell-right"><label for="q22a"><p>Then you will turn your body to punch to the attacker&#39;s face. Once you turn there&#39;s a kick to the groin, and you can open up the gap, make separation.</p></label></div></div><div class="qp-row"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q22" value="b" id="q22b"></div><div class="qp-m-answer-cell-middle">b.</div><div class="qp-m-answer-cell-right"><label for="q22b"><p>Then you there&#39;s a kick to the groin, and you can open up the gap, make separation.</p></label></div></div><div class="qp-row"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q22" value="c" id="q22c"></div><div class="qp-m-answer-cell-middle">c.</div><div class="qp-m-answer-cell-right"><label for="q22c"><p>Then you will turn your body to kick to the groin. Once you turn there&#39;s punch to the attacker&#39;s face and you can open up the gap, make separation.</p></label></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done22"></div><div class="collapse qpqfeedback2" id="feed22"></div></div></div>';
groupQpArray5[3]='<div id="quizpopper23"><div class="qpq"><form class="qp-form" name="f23"><div class="qp-the-question"><p>The last step while defending yourself against rear choke is resist the pull, which means you are going to move front to go against with him and resist his ability to take me over to that kind of position.</p></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q23" value="true" id="q23a"></div><div class="qp-t-f-cell-right"><label for="q23a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q23" value="false" id="q23b"></div><div class="qp-t-f-cell-right"><label for="q23b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done23"></div><div class="collapse qpqfeedback2" id="feed23"></div></div></div>';


groupFinished[6] = false;
firstDisplayed[6] = false;
currentQPNum[6] = 1;
var groupQpArray6 = new Array();
var groupQpStateArray6 = new Array();
var qpNumbersArray6 = new Array();
qpNumbersArray6[0] = 1;
qpNumbersArray6[1] = 2;
qpNumbersArray6[2] = 3;
quizGroupSize[6] = 3;
groupQpArray6[1]='<div id="quizpopper31"><div class="qpq"><form class="qp-form" name="f31"><div class="qp-the-question"><p>A gangster comes near you with a stick as a weapon. How would you defend yourself?</p></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-m-choice-cell-left"><input type="radio" name="q31" value="a" id="q31a"></div><div class="qp-m-choice-cell-middle">a.</div><div class="qp-m-choice-cell-right"><label for="q31a"><p>When the stick comes at you from the top, you close the gap and strike him straight to the face. Then run.</p></label></div></div><div class="qp-row"><div class="qp-m-choice-cell-left"><input type="radio" name="q31" value="b" id="q31b"></div><div class="qp-m-choice-cell-middle">b.</div><div class="qp-m-choice-cell-right"><label for="q31b"><p>When the stick comes at you from the top, our knee is going to attack him into the groin, isolation of the arm with the weapon, extract the weapon, strike him and open up spaces.</p></label></div></div><div class="qp-row"><div class="qp-m-choice-cell-left"><input type="radio" name="q31" value="c" id="q31c"></div><div class="qp-m-choice-cell-middle">c.</div><div class="qp-m-choice-cell-right"><label for="q31c"><p>When the stick comes at you from the top, you close the gap and strike him straight to the face. Then your knee is going to attack him into the groin, isolation of the arm with the weapon, extract the weapon, strike him and open up spaces.</p></label></div></div><div class="qp-row"><div class="qp-m-choice-cell-left"><input type="radio" name="q31" value="d" id="q31d"></div><div class="qp-m-choice-cell-middle">d.</div><div class="qp-m-choice-cell-right"><label for="q31d"><p>When the stick comes at you strike him and open up spaces.</p></label></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done31"></div><div class="collapse qpqfeedback2" id="feed31"></div></div></div>';
groupQpArray6[2]='<div id="quizpopper32"><div class="qpq"><form class="qp-form" name="f32"><div class="qp-the-question"><p>The first step while defending yourself against an attacker who has a knife as a weapon is to grab and punch the attacker, with a continuation of a kick to the groin and taking away the knife.</p></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q32" value="true" id="q32a"></div><div class="qp-t-f-cell-right"><label for="q32a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q32" value="false" id="q32b"></div><div class="qp-t-f-cell-right"><label for="q32b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done32"></div><div class="collapse qpqfeedback2" id="feed32"></div></div></div>';
groupQpArray6[3]='<div id="quizpopper33"><div class="qpq"><form class="qp-form" name="f33"><div class="qp-the-question"><div class="qp-bottom-margin"><p>Select the best answer choise. Nothing is guaranteed in defensive encounters, and there is always a risk of bodily injury or even death, this is especially true when <select class="form-control qp-select" id="q33_1"><option disabled selected></option><option>hammer</option><option>any weapons</option><option>guns</option><option>knife</option></select> get involved.</p></div></div></form><div class="collapse qpqfeedback" id="f_done33"></div><div class="collapse qpqfeedback2" id="feed33"></div></div></div>';


groupFinished[4] = false;
firstDisplayed[4] = false;
currentQPNum[4] = 1;
var groupQpArray4 = new Array();
var groupQpStateArray4 = new Array();
var qpNumbersArray4 = new Array();
qpNumbersArray4[0] = 1;
qpNumbersArray4[1] = 2;
qpNumbersArray4[2] = 3;
qpNumbersArray4[3] = 4;
qpNumbersArray4[4] = 5;
qpNumbersArray4[5] = 6;
qpNumbersArray4[6] = 7;
quizGroupSize[4] = 7;
groupQpArray4[1]='<div id="quizpopper19"><div class="qpqvalue">Value: 3</div><div class="qpq"><form class="qp-form" name="f19"><div class="qp-the-question"><p>Krav Maga Worldwide teaches street self-defense using:</p><p>&nbsp;</p></div><div class="qpindent"><div class="qp-m-answer-instruction">[mark all correct answers]</div><div class="qp-table"><div class="qp-row"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q19" value="a" id="q19a"></div><div class="qp-m-answer-cell-middle">a.</div><div class="qp-m-answer-cell-right"><label for="q19a"><p>Punches, knees, elbows, and kicks</p><p>&nbsp;</p></label></div></div><div class="qp-row"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q19" value="b" id="q19b"></div><div class="qp-m-answer-cell-middle">b.</div><div class="qp-m-answer-cell-right"><label for="q19b"><p>Defenses against various strikes, weapons, and chokes</p></label></div></div><div class="qp-row"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q19" value="c" id="q19c"></div><div class="qp-m-answer-cell-middle">c.</div><div class="qp-m-answer-cell-right"><label for="q19c"><p>Defense against spritual beings</p></label></div></div><div class="qp-row"><div class="qp-m-answer-cell-left"><input type="checkbox" name="q19" value="d" id="q19d"></div><div class="qp-m-answer-cell-middle">d.</div><div class="qp-m-answer-cell-right"><label for="q19d"><p>Realistic training drills</p></label></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done19"></div><div class="collapse qpqfeedback2" id="feed19"></div></div></div>';
groupQpArray4[2]='<div id="quizpopper14"><div class="qpqvalue">Value: 3</div><div class="qpq"><form class="qp-form" name="f14"><div class="qp-the-question"><p>Why is self-defense important? Also explain about the importance of self-defense for women.</p><p>[This part of the question is not auto-generated so your instructor will review your answers after you submit it.]</p></div><div class="qpindent"><textarea class="form-control" name="q14" id="q14" rows="16" cols="46" onfocus="clearEssayFeedback(14)"></textarea></div><div class="qpqcheckbutton"><input onclick="check_q(14, 0, 8, true)" type="button" class="btn btn-default" name="essay_button" value="Finish"><span class="qp-between-button-space"></span><input onclick="print_essay(14)" type="button" class="btn btn-default" name="Print" value="Print"></div></form><div class="collapse qpqfeedback" id="f_done14"></div><div class="collapse qpqfeedback2" id="feed14"></div></div></div>';
groupQpArray4[3]='<div id="quizpopper17"><div class="qpqvalue">Value: 3</div><div class="qpq"><form class="qp-form" name="f17"><div class="qp-the-question"><p>A stranger comes up to you and grabs your T-shirt from the front. What would you do? Put the steps in the correct order.</p></div><div class="hideqpstuff">Below is a sequence of events. Place them in the order they should occur, number 1 being the first item. Select the step number from the drop down next to each item.</div><div class="qpindent"><div class="hideqpstuff">Items to order:<div>1. <p>You are going to knee him in the groin.</p></div><div>2. <p>Cut with an elbow across the face, opening the gap.</p></div><div>3. <p>When he grabs, you take that shoulder to the rear, bring one hand to protect your face and the other hand directly into his face.</p></div></div><div class="qp-table"><div class="qp-row"><div class="qp-ordering-cell-left"><label for="q17_1"><p>You are going to knee him in the groin.</p></label></div><div class="qp-ordering-cell-right"><select class="form-control qp-select" name="q17_1" id="q17_1"><option>1</option><option>2</option><option>3</option></select></div></div><div class="qp-row"><div class="qp-ordering-cell-left"><label for="q17_2"><p>Cut with an elbow across the face, opening the gap.</p></label></div><div class="qp-ordering-cell-right"><select class="form-control qp-select" name="q17_2" id="q17_2"><option>1</option><option>2</option><option>3</option></select></div></div><div class="qp-row"><div class="qp-ordering-cell-left"><label for="q17_3"><p>When he grabs, you take that shoulder to the rear, bring one hand to protect your face and the other hand directly into his face.</p></label></div><div class="qp-ordering-cell-right"><select class="form-control qp-select" name="q17_3" id="q17_3"><option>1</option><option>2</option><option>3</option></select></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done17"></div><div class="collapse qpqfeedback2" id="feed17"></div></div></div>';
groupQpArray4[4]='<div id="quizpopper25"><div class="qpqvalue">Value: 3</div><div class="qpq"><form class="qp-form" name="f25"><div class="qp-the-question"><p>While defending yourself against front bear hug, as you strike to create space you want to establish your base to get balanced and to do this you step back with one leg into essentially a fighting stance.</p></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q25" value="true" id="q25a"></div><div class="qp-t-f-cell-right"><label for="q25a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q25" value="false" id="q25b"></div><div class="qp-t-f-cell-right"><label for="q25b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done25"></div><div class="collapse qpqfeedback2" id="feed25"></div></div></div>';
groupQpArray4[5]='<div id="quizpopper26"><div class="qpqvalue">Value: 3</div><div class="qpq"><form class="qp-form" name="f26"><div class="qp-the-question"><p>The key to most Krav Maga techniques is you go off very slowly with less speed, no aggression, and no violence until you are safe.</p></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q26" value="true" id="q26a"></div><div class="qp-t-f-cell-right"><label for="q26a"><span class="qp-t-f-answer">True</span></label></div></div><div class="qp-row"><div class="qp-t-f-cell-left"><input type="radio" name="q26" value="false" id="q26b"></div><div class="qp-t-f-cell-right"><label for="q26b"><span class="qp-t-f-answer">False</span></label></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done26"></div><div class="collapse qpqfeedback2" id="feed26"></div></div></div>';
groupQpArray4[6]='<div id="quizpopper27"><div class="qpqvalue">Value: 2</div><div class="qpq"><form class="qp-form" name="f27"><div class="qp-the-question"><div class="qp-bottom-margin"><p>Bear hugs can be the start to a very dangerous scenario especially when applied to <input type="text" class="form-control qp-select" size="10" id="q27_1">.</p></div></div></form><div class="collapse qpqfeedback" id="f_done27"></div><div class="collapse qpqfeedback2" id="feed27"></div></div></div>';
groupQpArray4[7]='<div id="quizpopper30"><div class="qpqvalue">Value: 3</div><div class="qpq"><form class="qp-form" name="f30"><div class="qp-the-question"><p>When you see a gun, there&#39;s two motions that are going carry out. Which is the most important step?</p><p>&nbsp;</p></div><div class="qpindent"><div class="qp-table"><div class="qp-row"><div class="qp-m-choice-cell-left"><input type="radio" name="q30" value="a" id="q30a"></div><div class="qp-m-choice-cell-middle">a.</div><div class="qp-m-choice-cell-right"><label for="q30a"><p>Run away</p></label></div></div><div class="qp-row"><div class="qp-m-choice-cell-left"><input type="radio" name="q30" value="b" id="q30b"></div><div class="qp-m-choice-cell-middle">b.</div><div class="qp-m-choice-cell-right"><label for="q30b"><p>Move off the line of fire</p></label></div></div><div class="qp-row"><div class="qp-m-choice-cell-left"><input type="radio" name="q30" value="c" id="q30c"></div><div class="qp-m-choice-cell-middle">c.</div><div class="qp-m-choice-cell-right"><label for="q30c"><p>Take the gun</p></label></div></div><div class="qp-row"><div class="qp-m-choice-cell-left"><input type="radio" name="q30" value="d" id="q30d"></div><div class="qp-m-choice-cell-middle">d.</div><div class="qp-m-choice-cell-right"><label for="q30d"><p>Barrell into the attacker</p></label></div></div></div></div></form><div class="collapse qpqfeedback" id="f_done30"></div><div class="collapse qpqfeedback2" id="feed30"></div></div></div>';

